// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service/synchronization/synchronization.proto

package synchronization

import (
	selection "github.com/mutagen-io/mutagen/pkg/selection"
	synchronization "github.com/mutagen-io/mutagen/pkg/synchronization"
	url "github.com/mutagen-io/mutagen/pkg/url"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreationSpecification contains the metadata required for a new session.
type CreationSpecification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alpha is the alpha endpoint URL for the session.
	Alpha *url.URL `protobuf:"bytes,1,opt,name=alpha,proto3" json:"alpha,omitempty"`
	// Beta is the beta endpoint URL for the session.
	Beta *url.URL `protobuf:"bytes,2,opt,name=beta,proto3" json:"beta,omitempty"`
	// Configuration is the base session configuration. It is the result of
	// merging the global configuration (unless disabled), any manually
	// specified configuration file, and any command line configuration
	// parameters.
	Configuration *synchronization.Configuration `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// ConfigurationAlpha is the alpha-specific session configuration. It is
	// determined based on command line configuration parameters.
	ConfigurationAlpha *synchronization.Configuration `protobuf:"bytes,4,opt,name=configurationAlpha,proto3" json:"configurationAlpha,omitempty"`
	// ConfigurationBeta is the beta-specific session configuration. It is
	// determined based on command line configuration parameters.
	ConfigurationBeta *synchronization.Configuration `protobuf:"bytes,5,opt,name=configurationBeta,proto3" json:"configurationBeta,omitempty"`
	// Name is the name for the session object.
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// Labels are the labels for the session object.
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Paused indicates whether or not to create the session pre-paused.
	Paused        bool `protobuf:"varint,8,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreationSpecification) Reset() {
	*x = CreationSpecification{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreationSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreationSpecification) ProtoMessage() {}

func (x *CreationSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreationSpecification.ProtoReflect.Descriptor instead.
func (*CreationSpecification) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{0}
}

func (x *CreationSpecification) GetAlpha() *url.URL {
	if x != nil {
		return x.Alpha
	}
	return nil
}

func (x *CreationSpecification) GetBeta() *url.URL {
	if x != nil {
		return x.Beta
	}
	return nil
}

func (x *CreationSpecification) GetConfiguration() *synchronization.Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *CreationSpecification) GetConfigurationAlpha() *synchronization.Configuration {
	if x != nil {
		return x.ConfigurationAlpha
	}
	return nil
}

func (x *CreationSpecification) GetConfigurationBeta() *synchronization.Configuration {
	if x != nil {
		return x.ConfigurationBeta
	}
	return nil
}

func (x *CreationSpecification) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreationSpecification) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreationSpecification) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

// CreateRequest encodes a request for session creation.
type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prompter is the prompter identifier to use for creating sessions.
	Prompter string `protobuf:"bytes,1,opt,name=prompter,proto3" json:"prompter,omitempty"`
	// Specification is the creation specification.
	Specification *CreationSpecification `protobuf:"bytes,2,opt,name=specification,proto3" json:"specification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetPrompter() string {
	if x != nil {
		return x.Prompter
	}
	return ""
}

func (x *CreateRequest) GetSpecification() *CreationSpecification {
	if x != nil {
		return x.Specification
	}
	return nil
}

// CreateResponse encodes a session creation response.
type CreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session is the resulting session identifier.
	Session       string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

// ListRequest encodes a request for session metadata.
type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Selection is the session selection criteria.
	Selection *selection.Selection `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
	// PreviousStateIndex is the previously seen state index. 0 may be provided
	// to force an immediate state listing.
	PreviousStateIndex uint64 `protobuf:"varint,2,opt,name=previousStateIndex,proto3" json:"previousStateIndex,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetSelection() *selection.Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *ListRequest) GetPreviousStateIndex() uint64 {
	if x != nil {
		return x.PreviousStateIndex
	}
	return 0
}

// ListResponse encodes session metadata.
type ListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// StateIndex is the state index associated with the session metadata.
	StateIndex uint64 `protobuf:"varint,1,opt,name=stateIndex,proto3" json:"stateIndex,omitempty"`
	// SessionStates are the session metadata states.
	SessionStates []*synchronization.State `protobuf:"bytes,2,rep,name=sessionStates,proto3" json:"sessionStates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetStateIndex() uint64 {
	if x != nil {
		return x.StateIndex
	}
	return 0
}

func (x *ListResponse) GetSessionStates() []*synchronization.State {
	if x != nil {
		return x.SessionStates
	}
	return nil
}

// FlushRequest encodes a request to flush sessions.
type FlushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prompter is the prompter to use for status message updates.
	Prompter string `protobuf:"bytes,1,opt,name=prompter,proto3" json:"prompter,omitempty"`
	// Selection is the session selection criteria.
	Selection *selection.Selection `protobuf:"bytes,2,opt,name=selection,proto3" json:"selection,omitempty"`
	// SkipWait indicates whether or not the operation should avoid blocking.
	SkipWait      bool `protobuf:"varint,3,opt,name=skipWait,proto3" json:"skipWait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{5}
}

func (x *FlushRequest) GetPrompter() string {
	if x != nil {
		return x.Prompter
	}
	return ""
}

func (x *FlushRequest) GetSelection() *selection.Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *FlushRequest) GetSkipWait() bool {
	if x != nil {
		return x.SkipWait
	}
	return false
}

// FlushResponse indicates completion of flush operation(s).
type FlushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{6}
}

// PauseRequest encodes a request to pause sessions.
type PauseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prompter is the prompter to use for status message updates.
	Prompter string `protobuf:"bytes,1,opt,name=prompter,proto3" json:"prompter,omitempty"`
	// Selection is the session selection criteria.
	Selection     *selection.Selection `protobuf:"bytes,2,opt,name=selection,proto3" json:"selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRequest) Reset() {
	*x = PauseRequest{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRequest) ProtoMessage() {}

func (x *PauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRequest.ProtoReflect.Descriptor instead.
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{7}
}

func (x *PauseRequest) GetPrompter() string {
	if x != nil {
		return x.Prompter
	}
	return ""
}

func (x *PauseRequest) GetSelection() *selection.Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

// PauseResponse indicates completion of pause operation(s).
type PauseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseResponse) Reset() {
	*x = PauseResponse{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseResponse) ProtoMessage() {}

func (x *PauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseResponse.ProtoReflect.Descriptor instead.
func (*PauseResponse) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{8}
}

// ResumeRequest encodes a request to resume sessions.
type ResumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prompter is the prompter identifier to use for resuming sessions.
	Prompter string `protobuf:"bytes,1,opt,name=prompter,proto3" json:"prompter,omitempty"`
	// Selection is the session selection criteria.
	Selection     *selection.Selection `protobuf:"bytes,2,opt,name=selection,proto3" json:"selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeRequest) GetPrompter() string {
	if x != nil {
		return x.Prompter
	}
	return ""
}

func (x *ResumeRequest) GetSelection() *selection.Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

// ResumeResponse indicates completion of resume operation(s).
type ResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{10}
}

// ResetRequest encodes a request to reset sessions.
type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prompter is the prompter identifier to use for resetting sessions.
	Prompter string `protobuf:"bytes,1,opt,name=prompter,proto3" json:"prompter,omitempty"`
	// Selection is the session selection criteria.
	Selection     *selection.Selection `protobuf:"bytes,2,opt,name=selection,proto3" json:"selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{11}
}

func (x *ResetRequest) GetPrompter() string {
	if x != nil {
		return x.Prompter
	}
	return ""
}

func (x *ResetRequest) GetSelection() *selection.Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

// ResetResponse indicates completion of reset operation(s).
type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{12}
}

// TerminateRequest encodes a request to terminate sessions.
type TerminateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prompter is the prompter to use for status message updates.
	Prompter string `protobuf:"bytes,1,opt,name=prompter,proto3" json:"prompter,omitempty"`
	// Selection is the session selection criteria.
	Selection     *selection.Selection `protobuf:"bytes,2,opt,name=selection,proto3" json:"selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{13}
}

func (x *TerminateRequest) GetPrompter() string {
	if x != nil {
		return x.Prompter
	}
	return ""
}

func (x *TerminateRequest) GetSelection() *selection.Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

// TerminateResponse indicates completion of termination operation(s).
type TerminateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	mi := &file_service_synchronization_synchronization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_synchronization_synchronization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_service_synchronization_synchronization_proto_rawDescGZIP(), []int{14}
}

var File_service_synchronization_synchronization_proto protoreflect.FileDescriptor

const file_service_synchronization_synchronization_proto_rawDesc = "" +
	"\n" +
	"-service/synchronization/synchronization.proto\x12\x0fsynchronization\x1a\x19selection/selection.proto\x1a#synchronization/configuration.proto\x1a\x1bsynchronization/state.proto\x1a\rurl/url.proto\"\xec\x03\n" +
	"\x15CreationSpecification\x12\x1e\n" +
	"\x05alpha\x18\x01 \x01(\v2\b.url.URLR\x05alpha\x12\x1c\n" +
	"\x04beta\x18\x02 \x01(\v2\b.url.URLR\x04beta\x12D\n" +
	"\rconfiguration\x18\x03 \x01(\v2\x1e.synchronization.ConfigurationR\rconfiguration\x12N\n" +
	"\x12configurationAlpha\x18\x04 \x01(\v2\x1e.synchronization.ConfigurationR\x12configurationAlpha\x12L\n" +
	"\x11configurationBeta\x18\x05 \x01(\v2\x1e.synchronization.ConfigurationR\x11configurationBeta\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12J\n" +
	"\x06labels\x18\a \x03(\v22.synchronization.CreationSpecification.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06paused\x18\b \x01(\bR\x06paused\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\rCreateRequest\x12\x1a\n" +
	"\bprompter\x18\x01 \x01(\tR\bprompter\x12L\n" +
	"\rspecification\x18\x02 \x01(\v2&.synchronization.CreationSpecificationR\rspecification\"*\n" +
	"\x0eCreateResponse\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"q\n" +
	"\vListRequest\x122\n" +
	"\tselection\x18\x01 \x01(\v2\x14.selection.SelectionR\tselection\x12.\n" +
	"\x12previousStateIndex\x18\x02 \x01(\x04R\x12previousStateIndex\"l\n" +
	"\fListResponse\x12\x1e\n" +
	"\n" +
	"stateIndex\x18\x01 \x01(\x04R\n" +
	"stateIndex\x12<\n" +
	"\rsessionStates\x18\x02 \x03(\v2\x16.synchronization.StateR\rsessionStates\"z\n" +
	"\fFlushRequest\x12\x1a\n" +
	"\bprompter\x18\x01 \x01(\tR\bprompter\x122\n" +
	"\tselection\x18\x02 \x01(\v2\x14.selection.SelectionR\tselection\x12\x1a\n" +
	"\bskipWait\x18\x03 \x01(\bR\bskipWait\"\x0f\n" +
	"\rFlushResponse\"^\n" +
	"\fPauseRequest\x12\x1a\n" +
	"\bprompter\x18\x01 \x01(\tR\bprompter\x122\n" +
	"\tselection\x18\x02 \x01(\v2\x14.selection.SelectionR\tselection\"\x0f\n" +
	"\rPauseResponse\"_\n" +
	"\rResumeRequest\x12\x1a\n" +
	"\bprompter\x18\x01 \x01(\tR\bprompter\x122\n" +
	"\tselection\x18\x02 \x01(\v2\x14.selection.SelectionR\tselection\"\x10\n" +
	"\x0eResumeResponse\"^\n" +
	"\fResetRequest\x12\x1a\n" +
	"\bprompter\x18\x01 \x01(\tR\bprompter\x122\n" +
	"\tselection\x18\x02 \x01(\v2\x14.selection.SelectionR\tselection\"\x0f\n" +
	"\rResetResponse\"b\n" +
	"\x10TerminateRequest\x12\x1a\n" +
	"\bprompter\x18\x01 \x01(\tR\bprompter\x122\n" +
	"\tselection\x18\x02 \x01(\v2\x14.selection.SelectionR\tselection\"\x13\n" +
	"\x11TerminateResponse2\xa6\x04\n" +
	"\x0fSynchronization\x12K\n" +
	"\x06Create\x12\x1e.synchronization.CreateRequest\x1a\x1f.synchronization.CreateResponse\"\x00\x12E\n" +
	"\x04List\x12\x1c.synchronization.ListRequest\x1a\x1d.synchronization.ListResponse\"\x00\x12H\n" +
	"\x05Flush\x12\x1d.synchronization.FlushRequest\x1a\x1e.synchronization.FlushResponse\"\x00\x12H\n" +
	"\x05Pause\x12\x1d.synchronization.PauseRequest\x1a\x1e.synchronization.PauseResponse\"\x00\x12K\n" +
	"\x06Resume\x12\x1e.synchronization.ResumeRequest\x1a\x1f.synchronization.ResumeResponse\"\x00\x12H\n" +
	"\x05Reset\x12\x1d.synchronization.ResetRequest\x1a\x1e.synchronization.ResetResponse\"\x00\x12T\n" +
	"\tTerminate\x12!.synchronization.TerminateRequest\x1a\".synchronization.TerminateResponse\"\x00B;Z9github.com/mutagen-io/mutagen/pkg/service/synchronizationb\x06proto3"

var (
	file_service_synchronization_synchronization_proto_rawDescOnce sync.Once
	file_service_synchronization_synchronization_proto_rawDescData []byte
)

func file_service_synchronization_synchronization_proto_rawDescGZIP() []byte {
	file_service_synchronization_synchronization_proto_rawDescOnce.Do(func() {
		file_service_synchronization_synchronization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_synchronization_synchronization_proto_rawDesc), len(file_service_synchronization_synchronization_proto_rawDesc)))
	})
	return file_service_synchronization_synchronization_proto_rawDescData
}

var file_service_synchronization_synchronization_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_service_synchronization_synchronization_proto_goTypes = []any{
	(*CreationSpecification)(nil),         // 0: synchronization.CreationSpecification
	(*CreateRequest)(nil),                 // 1: synchronization.CreateRequest
	(*CreateResponse)(nil),                // 2: synchronization.CreateResponse
	(*ListRequest)(nil),                   // 3: synchronization.ListRequest
	(*ListResponse)(nil),                  // 4: synchronization.ListResponse
	(*FlushRequest)(nil),                  // 5: synchronization.FlushRequest
	(*FlushResponse)(nil),                 // 6: synchronization.FlushResponse
	(*PauseRequest)(nil),                  // 7: synchronization.PauseRequest
	(*PauseResponse)(nil),                 // 8: synchronization.PauseResponse
	(*ResumeRequest)(nil),                 // 9: synchronization.ResumeRequest
	(*ResumeResponse)(nil),                // 10: synchronization.ResumeResponse
	(*ResetRequest)(nil),                  // 11: synchronization.ResetRequest
	(*ResetResponse)(nil),                 // 12: synchronization.ResetResponse
	(*TerminateRequest)(nil),              // 13: synchronization.TerminateRequest
	(*TerminateResponse)(nil),             // 14: synchronization.TerminateResponse
	nil,                                   // 15: synchronization.CreationSpecification.LabelsEntry
	(*url.URL)(nil),                       // 16: url.URL
	(*synchronization.Configuration)(nil), // 17: synchronization.Configuration
	(*selection.Selection)(nil),           // 18: selection.Selection
	(*synchronization.State)(nil),         // 19: synchronization.State
}
var file_service_synchronization_synchronization_proto_depIdxs = []int32{
	16, // 0: synchronization.CreationSpecification.alpha:type_name -> url.URL
	16, // 1: synchronization.CreationSpecification.beta:type_name -> url.URL
	17, // 2: synchronization.CreationSpecification.configuration:type_name -> synchronization.Configuration
	17, // 3: synchronization.CreationSpecification.configurationAlpha:type_name -> synchronization.Configuration
	17, // 4: synchronization.CreationSpecification.configurationBeta:type_name -> synchronization.Configuration
	15, // 5: synchronization.CreationSpecification.labels:type_name -> synchronization.CreationSpecification.LabelsEntry
	0,  // 6: synchronization.CreateRequest.specification:type_name -> synchronization.CreationSpecification
	18, // 7: synchronization.ListRequest.selection:type_name -> selection.Selection
	19, // 8: synchronization.ListResponse.sessionStates:type_name -> synchronization.State
	18, // 9: synchronization.FlushRequest.selection:type_name -> selection.Selection
	18, // 10: synchronization.PauseRequest.selection:type_name -> selection.Selection
	18, // 11: synchronization.ResumeRequest.selection:type_name -> selection.Selection
	18, // 12: synchronization.ResetRequest.selection:type_name -> selection.Selection
	18, // 13: synchronization.TerminateRequest.selection:type_name -> selection.Selection
	1,  // 14: synchronization.Synchronization.Create:input_type -> synchronization.CreateRequest
	3,  // 15: synchronization.Synchronization.List:input_type -> synchronization.ListRequest
	5,  // 16: synchronization.Synchronization.Flush:input_type -> synchronization.FlushRequest
	7,  // 17: synchronization.Synchronization.Pause:input_type -> synchronization.PauseRequest
	9,  // 18: synchronization.Synchronization.Resume:input_type -> synchronization.ResumeRequest
	11, // 19: synchronization.Synchronization.Reset:input_type -> synchronization.ResetRequest
	13, // 20: synchronization.Synchronization.Terminate:input_type -> synchronization.TerminateRequest
	2,  // 21: synchronization.Synchronization.Create:output_type -> synchronization.CreateResponse
	4,  // 22: synchronization.Synchronization.List:output_type -> synchronization.ListResponse
	6,  // 23: synchronization.Synchronization.Flush:output_type -> synchronization.FlushResponse
	8,  // 24: synchronization.Synchronization.Pause:output_type -> synchronization.PauseResponse
	10, // 25: synchronization.Synchronization.Resume:output_type -> synchronization.ResumeResponse
	12, // 26: synchronization.Synchronization.Reset:output_type -> synchronization.ResetResponse
	14, // 27: synchronization.Synchronization.Terminate:output_type -> synchronization.TerminateResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_service_synchronization_synchronization_proto_init() }
func file_service_synchronization_synchronization_proto_init() {
	if File_service_synchronization_synchronization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_synchronization_synchronization_proto_rawDesc), len(file_service_synchronization_synchronization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_synchronization_synchronization_proto_goTypes,
		DependencyIndexes: file_service_synchronization_synchronization_proto_depIdxs,
		MessageInfos:      file_service_synchronization_synchronization_proto_msgTypes,
	}.Build()
	File_service_synchronization_synchronization_proto = out.File
	file_service_synchronization_synchronization_proto_goTypes = nil
	file_service_synchronization_synchronization_proto_depIdxs = nil
}
