// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session/configuration.proto

package session // import "github.com/havoc-io/mutagen/pkg/session"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import filesystem "github.com/havoc-io/mutagen/pkg/filesystem"
import sync "github.com/havoc-io/mutagen/pkg/sync"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Configuration encodes session configuration parameters. It is used for create
// commands to specify configuration options, for loading global configuration
// options, and for storing a merged configuration inside sessions.
type Configuration struct {
	// SynchronizationMode specifies the synchronization mode that should be
	// used in synchronization.
	SynchronizationMode sync.SynchronizationMode `protobuf:"varint,11,opt,name=synchronizationMode,proto3,enum=sync.SynchronizationMode" json:"synchronizationMode,omitempty"`
	// SymlinkMode specifies the symlink mode that should be used in
	// synchronization.
	SymlinkMode sync.SymlinkMode `protobuf:"varint,1,opt,name=symlinkMode,proto3,enum=sync.SymlinkMode" json:"symlinkMode,omitempty"`
	// WatchMode specifies the filesystem watching mode.
	WatchMode filesystem.WatchMode `protobuf:"varint,21,opt,name=watchMode,proto3,enum=filesystem.WatchMode" json:"watchMode,omitempty"`
	// WatchPollingInterval specifies the interval (in seconds) for poll-based
	// file monitoring. A value of 0 specifies that the default interval should
	// be used.
	WatchPollingInterval uint32 `protobuf:"varint,22,opt,name=watchPollingInterval,proto3" json:"watchPollingInterval,omitempty"`
	// DefaultIgnores specifies the ignore patterns brought in from the global
	// configuration.
	DefaultIgnores []string `protobuf:"bytes,31,rep,name=defaultIgnores,proto3" json:"defaultIgnores,omitempty"`
	// Ignores specifies the ignore patterns brought in from the create request.
	Ignores []string `protobuf:"bytes,32,rep,name=ignores,proto3" json:"ignores,omitempty"`
	// IgnoreVCSMode specifies the VCS ignore mode that should be used in
	// synchronization.
	IgnoreVCSMode        sync.IgnoreVCSMode `protobuf:"varint,33,opt,name=ignoreVCSMode,proto3,enum=sync.IgnoreVCSMode" json:"ignoreVCSMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_3ac06fd96936abfc, []int{0}
}
func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (dst *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(dst, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetSynchronizationMode() sync.SynchronizationMode {
	if m != nil {
		return m.SynchronizationMode
	}
	return sync.SynchronizationMode_SynchronizationModeDefault
}

func (m *Configuration) GetSymlinkMode() sync.SymlinkMode {
	if m != nil {
		return m.SymlinkMode
	}
	return sync.SymlinkMode_SymlinkDefault
}

func (m *Configuration) GetWatchMode() filesystem.WatchMode {
	if m != nil {
		return m.WatchMode
	}
	return filesystem.WatchMode_WatchDefault
}

func (m *Configuration) GetWatchPollingInterval() uint32 {
	if m != nil {
		return m.WatchPollingInterval
	}
	return 0
}

func (m *Configuration) GetDefaultIgnores() []string {
	if m != nil {
		return m.DefaultIgnores
	}
	return nil
}

func (m *Configuration) GetIgnores() []string {
	if m != nil {
		return m.Ignores
	}
	return nil
}

func (m *Configuration) GetIgnoreVCSMode() sync.IgnoreVCSMode {
	if m != nil {
		return m.IgnoreVCSMode
	}
	return sync.IgnoreVCSMode_IgnoreVCSDefault
}

func init() {
	proto.RegisterType((*Configuration)(nil), "session.Configuration")
}

func init() {
	proto.RegisterFile("session/configuration.proto", fileDescriptor_configuration_3ac06fd96936abfc)
}

var fileDescriptor_configuration_3ac06fd96936abfc = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x83, 0x26, 0x12, 0x4a, 0xc0, 0x50, 0x84, 0x4c, 0x3c, 0x38, 0x3d, 0x28, 0x1e, 0x5c,
	0x13, 0x38, 0x79, 0x95, 0x13, 0x31, 0x26, 0x66, 0x24, 0x9a, 0x78, 0x2b, 0xa3, 0x74, 0x0d, 0x5d,
	0x1f, 0x59, 0x3b, 0x0c, 0xfe, 0xe3, 0x5e, 0x0d, 0x6f, 0x9b, 0x4c, 0xe5, 0xd6, 0xf7, 0xfd, 0x7e,
	0xde, 0xaf, 0x3e, 0x72, 0x61, 0x85, 0xb5, 0x0a, 0x0c, 0x8b, 0xc0, 0x2c, 0x95, 0xcc, 0x52, 0xee,
	0x14, 0x98, 0x60, 0x9d, 0x82, 0x03, 0x5a, 0x2f, 0xcc, 0x41, 0x7f, 0xa9, 0xb4, 0xb0, 0x5b, 0xeb,
	0x44, 0xc2, 0x3e, 0xb8, 0x8b, 0xe2, 0x1c, 0x18, 0x74, 0xec, 0xd6, 0x44, 0x4c, 0x49, 0x03, 0xa9,
	0x28, 0xa4, 0x53, 0x94, 0x12, 0x58, 0x94, 0x02, 0x45, 0xc1, 0x6e, 0x13, 0xad, 0xcc, 0x2a, 0xd7,
	0xae, 0xbf, 0x8e, 0x48, 0x6b, 0x52, 0x6d, 0x48, 0x9f, 0x48, 0x77, 0xc7, 0xc5, 0x29, 0x18, 0xf5,
	0x89, 0xd2, 0x33, 0x2c, 0x84, 0xd7, 0xf4, 0x6b, 0xc3, 0xf6, 0xe8, 0x3c, 0xd8, 0x79, 0xc1, 0xec,
	0x3f, 0x10, 0x1e, 0xca, 0xa2, 0x63, 0xd2, 0x2c, 0xfa, 0x61, 0x91, 0x1a, 0x16, 0xe9, 0x94, 0x45,
	0x7e, 0x8c, 0xb0, 0x4a, 0xd1, 0x31, 0x69, 0xe0, 0x6a, 0x98, 0xd2, 0xc3, 0x94, 0x5e, 0xb0, 0xdf,
	0x3b, 0x78, 0x2b, 0xcd, 0x70, 0xcf, 0xd1, 0x11, 0x39, 0xc3, 0xe0, 0x05, 0xb4, 0x56, 0x46, 0x4e,
	0x8d, 0x13, 0xe9, 0x86, 0x6b, 0xaf, 0xef, 0xd7, 0x86, 0xad, 0xf0, 0xa0, 0x47, 0x6f, 0x48, 0x7b,
	0x21, 0x96, 0x3c, 0xd3, 0x6e, 0x8a, 0x1f, 0x67, 0xbd, 0x4b, 0xff, 0x78, 0xd8, 0x08, 0xff, 0xa8,
	0xd4, 0x23, 0x75, 0x55, 0x00, 0x3e, 0x02, 0x65, 0x48, 0x1f, 0x48, 0x2b, 0x7f, 0xbe, 0x4e, 0x66,
	0x38, 0xee, 0x15, 0x8e, 0xdb, 0xcd, 0x37, 0x9c, 0x56, 0xad, 0xf0, 0x37, 0xf9, 0x78, 0xf7, 0x7e,
	0x2b, 0x95, 0x8b, 0xb3, 0x79, 0x10, 0x41, 0xc2, 0x62, 0xbe, 0x81, 0xe8, 0x5e, 0x01, 0x4b, 0x32,
	0xc7, 0xa5, 0x30, 0x6c, 0xbd, 0x92, 0xac, 0x38, 0xfa, 0xfc, 0x04, 0x6f, 0x35, 0xfe, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x98, 0x4b, 0xcb, 0x6a, 0x23, 0x02, 0x00, 0x00,
}
