// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/havoc-io/mutagen/pkg/session/session.proto

package session

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import sync "github.com/havoc-io/mutagen/pkg/sync"
import url "github.com/havoc-io/mutagen/pkg/url"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Version int32

const (
	Version_Unknown  Version = 0
	Version_Version1 Version = 1
)

var Version_name = map[int32]string{
	0: "Unknown",
	1: "Version1",
}
var Version_value = map[string]int32{
	"Unknown":  0,
	"Version1": 1,
}

func (x Version) String() string {
	return proto.EnumName(Version_name, int32(x))
}
func (Version) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_session_a908cf892368b8a2, []int{0}
}

type Session struct {
	Identifier           string               `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Version              Version              `protobuf:"varint,2,opt,name=version,enum=session.Version" json:"version,omitempty"`
	CreationTime         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=creationTime" json:"creationTime,omitempty"`
	CreatingVersionMajor uint32               `protobuf:"varint,4,opt,name=creatingVersionMajor" json:"creatingVersionMajor,omitempty"`
	CreatingVersionMinor uint32               `protobuf:"varint,5,opt,name=creatingVersionMinor" json:"creatingVersionMinor,omitempty"`
	CreatingVersionPatch uint32               `protobuf:"varint,6,opt,name=creatingVersionPatch" json:"creatingVersionPatch,omitempty"`
	Alpha                *url.URL             `protobuf:"bytes,7,opt,name=alpha" json:"alpha,omitempty"`
	Beta                 *url.URL             `protobuf:"bytes,8,opt,name=beta" json:"beta,omitempty"`
	Ignores              []string             `protobuf:"bytes,9,rep,name=ignores" json:"ignores,omitempty"`
	Paused               bool                 `protobuf:"varint,10,opt,name=paused" json:"paused,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_a908cf892368b8a2, []int{0}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Session) GetVersion() Version {
	if m != nil {
		return m.Version
	}
	return Version_Unknown
}

func (m *Session) GetCreationTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

func (m *Session) GetCreatingVersionMajor() uint32 {
	if m != nil {
		return m.CreatingVersionMajor
	}
	return 0
}

func (m *Session) GetCreatingVersionMinor() uint32 {
	if m != nil {
		return m.CreatingVersionMinor
	}
	return 0
}

func (m *Session) GetCreatingVersionPatch() uint32 {
	if m != nil {
		return m.CreatingVersionPatch
	}
	return 0
}

func (m *Session) GetAlpha() *url.URL {
	if m != nil {
		return m.Alpha
	}
	return nil
}

func (m *Session) GetBeta() *url.URL {
	if m != nil {
		return m.Beta
	}
	return nil
}

func (m *Session) GetIgnores() []string {
	if m != nil {
		return m.Ignores
	}
	return nil
}

func (m *Session) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

// Archive is a wrapper around Entry that allows identification of non-existent
// directories. In-memory, a nil-Entry (that arrives without any error)
// represents an absence of content on the filesystem. Unfortunately, there is
// no way to represent that as an encoded message (an empty byte slice would
// successfully decode to an empty directory entry). By adding a level of
// indirection that allows for an unset root entry, we can encode Entry messages
// in a way that allows us to represent absence.
type Archive struct {
	Root                 *sync.Entry `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Archive) Reset()         { *m = Archive{} }
func (m *Archive) String() string { return proto.CompactTextString(m) }
func (*Archive) ProtoMessage()    {}
func (*Archive) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_a908cf892368b8a2, []int{1}
}
func (m *Archive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Archive.Unmarshal(m, b)
}
func (m *Archive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Archive.Marshal(b, m, deterministic)
}
func (dst *Archive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Archive.Merge(dst, src)
}
func (m *Archive) XXX_Size() int {
	return xxx_messageInfo_Archive.Size(m)
}
func (m *Archive) XXX_DiscardUnknown() {
	xxx_messageInfo_Archive.DiscardUnknown(m)
}

var xxx_messageInfo_Archive proto.InternalMessageInfo

func (m *Archive) GetRoot() *sync.Entry {
	if m != nil {
		return m.Root
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "session.Session")
	proto.RegisterType((*Archive)(nil), "session.Archive")
	proto.RegisterEnum("session.Version", Version_name, Version_value)
}

func init() {
	proto.RegisterFile("github.com/havoc-io/mutagen/pkg/session/session.proto", fileDescriptor_session_a908cf892368b8a2)
}

var fileDescriptor_session_a908cf892368b8a2 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x4b, 0xab, 0xd3, 0x40,
	0x14, 0x36, 0xf6, 0x31, 0xe9, 0x49, 0x95, 0x32, 0x88, 0x0c, 0x45, 0xda, 0x50, 0x5c, 0x84, 0x42,
	0x27, 0x1a, 0x71, 0x2b, 0xb8, 0x70, 0xa7, 0x20, 0x63, 0xeb, 0x7e, 0x92, 0x4e, 0x93, 0xb1, 0xcd,
	0x4c, 0x98, 0x4c, 0x2a, 0xfd, 0x39, 0xf7, 0x9f, 0x5e, 0xf2, 0x82, 0x7b, 0x2f, 0x81, 0x2e, 0x42,
	0xf8, 0x5e, 0xc9, 0xf9, 0xce, 0x81, 0xaf, 0xa9, 0xb4, 0x59, 0x15, 0xd3, 0x44, 0xe7, 0x61, 0xc6,
	0xaf, 0x3a, 0xd9, 0x49, 0x1d, 0xe6, 0x95, 0xe5, 0xa9, 0x50, 0x61, 0x71, 0x4e, 0xc3, 0x52, 0x94,
	0xa5, 0xd4, 0xaa, 0x7f, 0xd3, 0xc2, 0x68, 0xab, 0x31, 0xea, 0xe0, 0x72, 0x9d, 0x6a, 0x9d, 0x5e,
	0x44, 0xd8, 0xd0, 0x71, 0x75, 0x0a, 0xad, 0xcc, 0x45, 0x69, 0x79, 0x5e, 0xb4, 0xce, 0xe5, 0xa7,
	0xbb, 0x3f, 0xb8, 0xa9, 0x24, 0x14, 0xca, 0x9a, 0x5b, 0x97, 0xd8, 0xdd, 0x4b, 0x54, 0xe6, 0x52,
	0x3f, 0xad, 0x7d, 0xf3, 0x30, 0x02, 0xf4, 0xa7, 0x9d, 0x06, 0xaf, 0x00, 0xe4, 0x51, 0x28, 0x2b,
	0x4f, 0x52, 0x18, 0xe2, 0xf8, 0x4e, 0x30, 0x63, 0x4f, 0x18, 0xbc, 0x05, 0x74, 0x15, 0xa6, 0xb6,
	0x92, 0xd7, 0xbe, 0x13, 0xbc, 0x8d, 0x16, 0xb4, 0xef, 0xf5, 0xb7, 0xe5, 0x59, 0x6f, 0xc0, 0xdf,
	0x60, 0x9e, 0x18, 0xc1, 0xad, 0xd4, 0x6a, 0x2f, 0x73, 0x41, 0x46, 0xbe, 0x13, 0x78, 0xd1, 0x92,
	0xb6, 0x85, 0x69, 0x5f, 0x98, 0xee, 0xfb, 0xc2, 0xec, 0x99, 0x1f, 0x47, 0xf0, 0xae, 0xc5, 0x2a,
	0xed, 0xbe, 0xfd, 0x8b, 0xff, 0xd3, 0x86, 0x8c, 0x7d, 0x27, 0x78, 0xc3, 0x06, 0xb5, 0xa1, 0x8c,
	0x54, 0xda, 0x90, 0xc9, 0x70, 0xa6, 0xd6, 0x06, 0x32, 0xbf, 0xb9, 0x4d, 0x32, 0x32, 0x1d, 0xcc,
	0x34, 0x1a, 0x5e, 0xc1, 0x84, 0x5f, 0x8a, 0x8c, 0x13, 0xd4, 0x94, 0x72, 0x69, 0xbd, 0xce, 0x03,
	0xfb, 0xc9, 0x5a, 0x1a, 0x7f, 0x80, 0x71, 0x2c, 0x2c, 0x27, 0xee, 0x0b, 0xb9, 0x61, 0x31, 0x01,
	0x24, 0x53, 0xa5, 0x8d, 0x28, 0xc9, 0xcc, 0x1f, 0x05, 0x33, 0xd6, 0x43, 0xfc, 0x1e, 0xa6, 0x05,
	0xaf, 0x4a, 0x71, 0x24, 0xe0, 0x3b, 0x81, 0xcb, 0x3a, 0xb4, 0xd9, 0x02, 0xfa, 0x6e, 0x92, 0x4c,
	0x5e, 0x05, 0x5e, 0xc3, 0xd8, 0x68, 0x6d, 0x9b, 0xe3, 0x78, 0x91, 0x47, 0xeb, 0xf3, 0xd3, 0x1f,
	0xf5, 0xf9, 0x59, 0x23, 0x6c, 0x3f, 0x02, 0xea, 0x66, 0xc5, 0x1e, 0xa0, 0x83, 0x3a, 0x2b, 0xfd,
	0x5f, 0x2d, 0x5e, 0xe1, 0x39, 0xb8, 0x1d, 0xff, 0x79, 0xe1, 0xc4, 0xd3, 0x66, 0xff, 0x5f, 0x1e,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x6f, 0x03, 0x9d, 0xc0, 0x02, 0x00, 0x00,
}
