// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session/session.proto

package session

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import url "url"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Version specifies a session version, providing default behavior that can vary
// without affecting existing sessions.
type Version int32

const (
	// Invalid is the default session version and represents an unspecfied and
	// invalid version. It is used as a sanity check to ensure that version is
	// set for a session.
	Version_Invalid Version = 0
	// Version1 represents session version 1.
	Version_Version1 Version = 1
)

var Version_name = map[int32]string{
	0: "Invalid",
	1: "Version1",
}
var Version_value = map[string]int32{
	"Invalid":  0,
	"Version1": 1,
}

func (x Version) String() string {
	return proto.EnumName(Version_name, int32(x))
}
func (Version) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_session_f7e2b6be5b893fa4, []int{0}
}

type Session struct {
	Identifier           string               `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Version              Version              `protobuf:"varint,2,opt,name=version,proto3,enum=session.Version" json:"version,omitempty"`
	CreationTime         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	CreatingVersionMajor uint32               `protobuf:"varint,4,opt,name=creatingVersionMajor,proto3" json:"creatingVersionMajor,omitempty"`
	CreatingVersionMinor uint32               `protobuf:"varint,5,opt,name=creatingVersionMinor,proto3" json:"creatingVersionMinor,omitempty"`
	CreatingVersionPatch uint32               `protobuf:"varint,6,opt,name=creatingVersionPatch,proto3" json:"creatingVersionPatch,omitempty"`
	Alpha                *url.URL             `protobuf:"bytes,7,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Beta                 *url.URL             `protobuf:"bytes,8,opt,name=beta,proto3" json:"beta,omitempty"`
	Configuration        *Configuration       `protobuf:"bytes,9,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Paused               bool                 `protobuf:"varint,10,opt,name=paused,proto3" json:"paused,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_f7e2b6be5b893fa4, []int{0}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Session) GetVersion() Version {
	if m != nil {
		return m.Version
	}
	return Version_Invalid
}

func (m *Session) GetCreationTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

func (m *Session) GetCreatingVersionMajor() uint32 {
	if m != nil {
		return m.CreatingVersionMajor
	}
	return 0
}

func (m *Session) GetCreatingVersionMinor() uint32 {
	if m != nil {
		return m.CreatingVersionMinor
	}
	return 0
}

func (m *Session) GetCreatingVersionPatch() uint32 {
	if m != nil {
		return m.CreatingVersionPatch
	}
	return 0
}

func (m *Session) GetAlpha() *url.URL {
	if m != nil {
		return m.Alpha
	}
	return nil
}

func (m *Session) GetBeta() *url.URL {
	if m != nil {
		return m.Beta
	}
	return nil
}

func (m *Session) GetConfiguration() *Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *Session) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func init() {
	proto.RegisterType((*Session)(nil), "session.Session")
	proto.RegisterEnum("session.Version", Version_name, Version_value)
}

func init() { proto.RegisterFile("session/session.proto", fileDescriptor_session_f7e2b6be5b893fa4) }

var fileDescriptor_session_f7e2b6be5b893fa4 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4f, 0xc2, 0x30,
	0x18, 0xb6, 0xf2, 0xb1, 0xf1, 0x02, 0x86, 0x34, 0x4a, 0x9a, 0x69, 0x70, 0x31, 0x1e, 0x16, 0x0e,
	0x5b, 0xc4, 0xab, 0xf1, 0xe2, 0xc9, 0x44, 0x13, 0x53, 0xd1, 0x7b, 0x81, 0x32, 0x6a, 0xc6, 0xba,
	0x74, 0x1d, 0xff, 0xd0, 0xff, 0x65, 0x68, 0x3b, 0x02, 0x66, 0xa7, 0xe6, 0xf9, 0x7a, 0xfb, 0xf4,
	0x2d, 0x5c, 0x95, 0xbc, 0x2c, 0x85, 0xcc, 0x13, 0x77, 0xc6, 0x85, 0x92, 0x5a, 0x62, 0xcf, 0xc1,
	0xe0, 0x36, 0x95, 0x32, 0xcd, 0x78, 0x62, 0xe8, 0x45, 0xb5, 0x4e, 0xb4, 0xd8, 0xf2, 0x52, 0xb3,
	0x6d, 0x61, 0x9d, 0xc1, 0x75, 0x3d, 0x60, 0x29, 0xf3, 0xb5, 0x48, 0x2b, 0xc5, 0xf4, 0x61, 0x4c,
	0x30, 0xac, 0x54, 0x96, 0x54, 0x2a, 0xb3, 0xf0, 0xee, 0xb7, 0x05, 0xde, 0xa7, 0xb5, 0xe3, 0x09,
	0x80, 0x58, 0xf1, 0x5c, 0x8b, 0xb5, 0xe0, 0x8a, 0xa0, 0x10, 0x45, 0x3d, 0x7a, 0xc4, 0xe0, 0x29,
	0x78, 0x3b, 0xae, 0xf6, 0x56, 0x72, 0x1e, 0xa2, 0xe8, 0x62, 0x36, 0x8a, 0xeb, 0x8a, 0xdf, 0x96,
	0xa7, 0xb5, 0x01, 0x3f, 0xc3, 0x60, 0xa9, 0xb8, 0xb9, 0x78, 0x2e, 0xb6, 0x9c, 0xb4, 0x42, 0x14,
	0xf5, 0x67, 0x41, 0x6c, 0xbb, 0xc7, 0x75, 0xf7, 0x78, 0x5e, 0x77, 0xa7, 0x27, 0x7e, 0x3c, 0x83,
	0x4b, 0x8b, 0xf3, 0xd4, 0xcd, 0x7e, 0x67, 0x3f, 0x52, 0x91, 0x76, 0x88, 0xa2, 0x21, 0x6d, 0xd4,
	0x9a, 0x32, 0x22, 0x97, 0x8a, 0x74, 0x9a, 0x33, 0x7b, 0xad, 0x21, 0xf3, 0xc1, 0xf4, 0x72, 0x43,
	0xba, 0x8d, 0x19, 0xa3, 0xe1, 0x09, 0x74, 0x58, 0x56, 0x6c, 0x18, 0xf1, 0xcc, 0xa3, 0xfc, 0x78,
	0xbf, 0xce, 0x2f, 0xfa, 0x46, 0x2d, 0x8d, 0x6f, 0xa0, 0xbd, 0xe0, 0x9a, 0x11, 0xff, 0x9f, 0x6c,
	0x58, 0xfc, 0x04, 0xc3, 0x93, 0x7f, 0x21, 0x3d, 0x63, 0x1b, 0x1f, 0x76, 0xf9, 0x72, 0xac, 0xd2,
	0x53, 0x33, 0x1e, 0x43, 0xb7, 0x60, 0x55, 0xc9, 0x57, 0x04, 0x42, 0x14, 0xf9, 0xd4, 0xa1, 0xe9,
	0x3d, 0x78, 0xae, 0x23, 0xee, 0x83, 0xf7, 0x9a, 0xef, 0x58, 0x26, 0x56, 0xa3, 0x33, 0x3c, 0x00,
	0xdf, 0xf1, 0x0f, 0x23, 0xb4, 0xe8, 0x9a, 0xbd, 0x3f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x51,
	0xae, 0xb8, 0xfb, 0x63, 0x02, 0x00, 0x00,
}
