// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/havoc-io/mutagen/pkg/prompt/prompt.proto

package prompt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Prompt struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Prompt               string   `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prompt) Reset()         { *m = Prompt{} }
func (m *Prompt) String() string { return proto.CompactTextString(m) }
func (*Prompt) ProtoMessage()    {}
func (*Prompt) Descriptor() ([]byte, []int) {
	return fileDescriptor_prompt_0b4bcc8a6cd37f69, []int{0}
}
func (m *Prompt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prompt.Unmarshal(m, b)
}
func (m *Prompt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prompt.Marshal(b, m, deterministic)
}
func (dst *Prompt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prompt.Merge(dst, src)
}
func (m *Prompt) XXX_Size() int {
	return xxx_messageInfo_Prompt.Size(m)
}
func (m *Prompt) XXX_DiscardUnknown() {
	xxx_messageInfo_Prompt.DiscardUnknown(m)
}

var xxx_messageInfo_Prompt proto.InternalMessageInfo

func (m *Prompt) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Prompt) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

func init() {
	proto.RegisterType((*Prompt)(nil), "prompt.Prompt")
}

func init() {
	proto.RegisterFile("github.com/havoc-io/mutagen/pkg/prompt/prompt.proto", fileDescriptor_prompt_0b4bcc8a6cd37f69)
}

var fileDescriptor_prompt_0b4bcc8a6cd37f69 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x48, 0x2c, 0xcb, 0x4f, 0xd6, 0xcd, 0xcc, 0xd7,
	0xcf, 0x2d, 0x2d, 0x49, 0x4c, 0x4f, 0xcd, 0xd3, 0x2f, 0xc8, 0x4e, 0xd7, 0x2f, 0x28, 0xca, 0xcf,
	0x2d, 0x28, 0x81, 0x52, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92, 0x15,
	0x17, 0x5b, 0x00, 0x98, 0x25, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x0a, 0x89, 0x71, 0x41, 0x55, 0x4b, 0x30, 0x81,
	0x25, 0xa0, 0xbc, 0x24, 0x36, 0xb0, 0x51, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x1b,
	0xaa, 0x22, 0x81, 0x00, 0x00, 0x00,
}
