// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session/endpoint/remote/endpoint_protocol.proto

package remote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	rsync "github.com/havoc-io/mutagen/pkg/rsync"
	session "github.com/havoc-io/mutagen/pkg/session"
	sync "github.com/havoc-io/mutagen/pkg/sync"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// InitializeRequest encodes a request for endpoint initialization.
type InitializeRequest struct {
	// Root is the synchronization root path.
	Root string `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// Session is the session identifier.
	Session string `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	// Version is the session version.
	Version session.Version `protobuf:"varint,3,opt,name=version,proto3,enum=session.Version" json:"version,omitempty"`
	// Configuration is the session configuration.
	Configuration *session.Configuration `protobuf:"bytes,4,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// Alpha indicates whether or not the endpoint should behave as alpha (as
	// opposed to beta).
	Alpha                bool     `protobuf:"varint,5,opt,name=alpha,proto3" json:"alpha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeRequest) Reset()         { *m = InitializeRequest{} }
func (m *InitializeRequest) String() string { return proto.CompactTextString(m) }
func (*InitializeRequest) ProtoMessage()    {}
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{0}
}

func (m *InitializeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeRequest.Unmarshal(m, b)
}
func (m *InitializeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeRequest.Marshal(b, m, deterministic)
}
func (m *InitializeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeRequest.Merge(m, src)
}
func (m *InitializeRequest) XXX_Size() int {
	return xxx_messageInfo_InitializeRequest.Size(m)
}
func (m *InitializeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeRequest proto.InternalMessageInfo

func (m *InitializeRequest) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *InitializeRequest) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *InitializeRequest) GetVersion() session.Version {
	if m != nil {
		return m.Version
	}
	return session.Version_Invalid
}

func (m *InitializeRequest) GetConfiguration() *session.Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *InitializeRequest) GetAlpha() bool {
	if m != nil {
		return m.Alpha
	}
	return false
}

// InitializeResponse encodes initialization results.
type InitializeResponse struct {
	// Error is the error message (if any) resulting from initialization.
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeResponse) Reset()         { *m = InitializeResponse{} }
func (m *InitializeResponse) String() string { return proto.CompactTextString(m) }
func (*InitializeResponse) ProtoMessage()    {}
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{1}
}

func (m *InitializeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeResponse.Unmarshal(m, b)
}
func (m *InitializeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeResponse.Marshal(b, m, deterministic)
}
func (m *InitializeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeResponse.Merge(m, src)
}
func (m *InitializeResponse) XXX_Size() int {
	return xxx_messageInfo_InitializeResponse.Size(m)
}
func (m *InitializeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeResponse proto.InternalMessageInfo

func (m *InitializeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// PollRequest encodes a request for one-shot polling.
type PollRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PollRequest) Reset()         { *m = PollRequest{} }
func (m *PollRequest) String() string { return proto.CompactTextString(m) }
func (*PollRequest) ProtoMessage()    {}
func (*PollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{2}
}

func (m *PollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollRequest.Unmarshal(m, b)
}
func (m *PollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollRequest.Marshal(b, m, deterministic)
}
func (m *PollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollRequest.Merge(m, src)
}
func (m *PollRequest) XXX_Size() int {
	return xxx_messageInfo_PollRequest.Size(m)
}
func (m *PollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PollRequest proto.InternalMessageInfo

// PollCompletionRequest is paired with pollRequest and indicates a request for
// early polling completion or an acknowledgement of completion.
type PollCompletionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PollCompletionRequest) Reset()         { *m = PollCompletionRequest{} }
func (m *PollCompletionRequest) String() string { return proto.CompactTextString(m) }
func (*PollCompletionRequest) ProtoMessage()    {}
func (*PollCompletionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{3}
}

func (m *PollCompletionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollCompletionRequest.Unmarshal(m, b)
}
func (m *PollCompletionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollCompletionRequest.Marshal(b, m, deterministic)
}
func (m *PollCompletionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollCompletionRequest.Merge(m, src)
}
func (m *PollCompletionRequest) XXX_Size() int {
	return xxx_messageInfo_PollCompletionRequest.Size(m)
}
func (m *PollCompletionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PollCompletionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PollCompletionRequest proto.InternalMessageInfo

// PollResponse indicates polling completion.
type PollResponse struct {
	// Error is the error message (if any) resulting from polling.
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PollResponse) Reset()         { *m = PollResponse{} }
func (m *PollResponse) String() string { return proto.CompactTextString(m) }
func (*PollResponse) ProtoMessage()    {}
func (*PollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{4}
}

func (m *PollResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollResponse.Unmarshal(m, b)
}
func (m *PollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollResponse.Marshal(b, m, deterministic)
}
func (m *PollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollResponse.Merge(m, src)
}
func (m *PollResponse) XXX_Size() int {
	return xxx_messageInfo_PollResponse.Size(m)
}
func (m *PollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PollResponse proto.InternalMessageInfo

func (m *PollResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// ScanRequest encodes a request for a scan.
type ScanRequest struct {
	// BaseSnapshotSignature is the rsync signature to use as the base for
	// differentially transmitting snapshots.
	BaseSnapshotSignature *rsync.Signature `protobuf:"bytes,1,opt,name=baseSnapshotSignature,proto3" json:"baseSnapshotSignature,omitempty"`
	// Full indicates whether or not to force a full (warm) scan, temporarily
	// avoiding any acceleration that might be available on the endpoint.
	Full                 bool     `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{5}
}

func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetBaseSnapshotSignature() *rsync.Signature {
	if m != nil {
		return m.BaseSnapshotSignature
	}
	return nil
}

func (m *ScanRequest) GetFull() bool {
	if m != nil {
		return m.Full
	}
	return false
}

// ScanResponse encodes the results of a scan.
type ScanResponse struct {
	// SnapshotDelta are the operations need to reconstruct the snapshot against
	// the specified base.
	SnapshotDelta []*rsync.Operation `protobuf:"bytes,1,rep,name=snapshotDelta,proto3" json:"snapshotDelta,omitempty"`
	// PreservesExecutability indicates whether or not the scan root preserves
	// POSIX executability bits.
	PreservesExecutability bool `protobuf:"varint,2,opt,name=preservesExecutability,proto3" json:"preservesExecutability,omitempty"`
	// Error is the error message (if any) resulting from scanning.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// TryAgain indicates whether or not the error is ephermeral.
	TryAgain             bool     `protobuf:"varint,4,opt,name=tryAgain,proto3" json:"tryAgain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{6}
}

func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetSnapshotDelta() []*rsync.Operation {
	if m != nil {
		return m.SnapshotDelta
	}
	return nil
}

func (m *ScanResponse) GetPreservesExecutability() bool {
	if m != nil {
		return m.PreservesExecutability
	}
	return false
}

func (m *ScanResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ScanResponse) GetTryAgain() bool {
	if m != nil {
		return m.TryAgain
	}
	return false
}

// StageRequest encodes a request for staging.
type StageRequest struct {
	// Paths lists the paths that need to be staged.
	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	// Digests lists the digests for the paths that need to be staged. Its
	// length and contents correspond to that of Paths.
	Digests              [][]byte `protobuf:"bytes,2,rep,name=digests,proto3" json:"digests,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StageRequest) Reset()         { *m = StageRequest{} }
func (m *StageRequest) String() string { return proto.CompactTextString(m) }
func (*StageRequest) ProtoMessage()    {}
func (*StageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{7}
}

func (m *StageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StageRequest.Unmarshal(m, b)
}
func (m *StageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StageRequest.Marshal(b, m, deterministic)
}
func (m *StageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StageRequest.Merge(m, src)
}
func (m *StageRequest) XXX_Size() int {
	return xxx_messageInfo_StageRequest.Size(m)
}
func (m *StageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StageRequest proto.InternalMessageInfo

func (m *StageRequest) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *StageRequest) GetDigests() [][]byte {
	if m != nil {
		return m.Digests
	}
	return nil
}

// StageResponse encodes the results of staging initialization.
type StageResponse struct {
	// Paths are the paths that need to be staged (relative to the
	// synchronization root).
	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	// Signatures are the rsync signatures of the paths needing to be staged.
	Signatures []*rsync.Signature `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Error is the error message (if any) resulting from staging
	// initialization.
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StageResponse) Reset()         { *m = StageResponse{} }
func (m *StageResponse) String() string { return proto.CompactTextString(m) }
func (*StageResponse) ProtoMessage()    {}
func (*StageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{8}
}

func (m *StageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StageResponse.Unmarshal(m, b)
}
func (m *StageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StageResponse.Marshal(b, m, deterministic)
}
func (m *StageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StageResponse.Merge(m, src)
}
func (m *StageResponse) XXX_Size() int {
	return xxx_messageInfo_StageResponse.Size(m)
}
func (m *StageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StageResponse proto.InternalMessageInfo

func (m *StageResponse) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *StageResponse) GetSignatures() []*rsync.Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *StageResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// SupplyRequest indicates a request for supplying files.
type SupplyRequest struct {
	// Paths are the paths to provide (relative to the synchronization root).
	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	// Signatures are the rsync signatures of the paths needing to be staged.
	Signatures           []*rsync.Signature `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SupplyRequest) Reset()         { *m = SupplyRequest{} }
func (m *SupplyRequest) String() string { return proto.CompactTextString(m) }
func (*SupplyRequest) ProtoMessage()    {}
func (*SupplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{9}
}

func (m *SupplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupplyRequest.Unmarshal(m, b)
}
func (m *SupplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupplyRequest.Marshal(b, m, deterministic)
}
func (m *SupplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupplyRequest.Merge(m, src)
}
func (m *SupplyRequest) XXX_Size() int {
	return xxx_messageInfo_SupplyRequest.Size(m)
}
func (m *SupplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SupplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SupplyRequest proto.InternalMessageInfo

func (m *SupplyRequest) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *SupplyRequest) GetSignatures() []*rsync.Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// TransitionRequest encodes a request for transition application.
type TransitionRequest struct {
	// Transitions are the transitions that need to be applied.
	Transitions          []*sync.Change `protobuf:"bytes,1,rep,name=transitions,proto3" json:"transitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransitionRequest) Reset()         { *m = TransitionRequest{} }
func (m *TransitionRequest) String() string { return proto.CompactTextString(m) }
func (*TransitionRequest) ProtoMessage()    {}
func (*TransitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{10}
}

func (m *TransitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransitionRequest.Unmarshal(m, b)
}
func (m *TransitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransitionRequest.Marshal(b, m, deterministic)
}
func (m *TransitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransitionRequest.Merge(m, src)
}
func (m *TransitionRequest) XXX_Size() int {
	return xxx_messageInfo_TransitionRequest.Size(m)
}
func (m *TransitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransitionRequest proto.InternalMessageInfo

func (m *TransitionRequest) GetTransitions() []*sync.Change {
	if m != nil {
		return m.Transitions
	}
	return nil
}

// TransitionResponse encodes the results of transitioning.
type TransitionResponse struct {
	// Results are the resulting contents post-transition.
	// HACK: We have to use Archive to wrap our Entry results here because
	// Protocol Buffers won't encode a nil pointer in a repeated element in
	// certain cases, and the results of transitions may very well be nil. gob
	// also exhibits this problem.
	Results []*sync.Archive `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Problems are any problems encountered during the transition operation.
	Problems []*sync.Problem `protobuf:"bytes,2,rep,name=problems,proto3" json:"problems,omitempty"`
	// StagerMissingFiles indicates whether or not the endpoint's stager
	// indicated missing files during transitioning.
	StagerMissingFiles bool `protobuf:"varint,3,opt,name=stagerMissingFiles,proto3" json:"stagerMissingFiles,omitempty"`
	// Error is the error message (if any) resulting from the remote transition
	// method. This will always be an empty string since transition doesn't
	// return errors from local endpoints, but to match the endpoint interface
	// (which allows for transition errors due to network failures with remote
	// endpoints), we include this field.
	// TODO: Should we just remove this field? Doing so would rely on knowledge
	// of localEndpoint's transition behavior.
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransitionResponse) Reset()         { *m = TransitionResponse{} }
func (m *TransitionResponse) String() string { return proto.CompactTextString(m) }
func (*TransitionResponse) ProtoMessage()    {}
func (*TransitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{11}
}

func (m *TransitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransitionResponse.Unmarshal(m, b)
}
func (m *TransitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransitionResponse.Marshal(b, m, deterministic)
}
func (m *TransitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransitionResponse.Merge(m, src)
}
func (m *TransitionResponse) XXX_Size() int {
	return xxx_messageInfo_TransitionResponse.Size(m)
}
func (m *TransitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransitionResponse proto.InternalMessageInfo

func (m *TransitionResponse) GetResults() []*sync.Archive {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *TransitionResponse) GetProblems() []*sync.Problem {
	if m != nil {
		return m.Problems
	}
	return nil
}

func (m *TransitionResponse) GetStagerMissingFiles() bool {
	if m != nil {
		return m.StagerMissingFiles
	}
	return false
}

func (m *TransitionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// EndpointRequest is a sum type that can transmit any type of endpoint request.
// Only the sent request will be non-nil. We intentionally avoid using Protocol
// Buffers' oneof feature because it generates really ugly code and an unwieldy
// API, at least in Go. Manually checking for exclusivity is not difficult.
type EndpointRequest struct {
	// Poll represents a poll request.
	Poll *PollRequest `protobuf:"bytes,1,opt,name=poll,proto3" json:"poll,omitempty"`
	// Scan represents a scan request.
	Scan *ScanRequest `protobuf:"bytes,2,opt,name=scan,proto3" json:"scan,omitempty"`
	// Stage represents a stage request.
	Stage *StageRequest `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	// Supply represents a supply request.
	Supply *SupplyRequest `protobuf:"bytes,4,opt,name=supply,proto3" json:"supply,omitempty"`
	// Transition represents a transition request.
	Transition           *TransitionRequest `protobuf:"bytes,5,opt,name=transition,proto3" json:"transition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EndpointRequest) Reset()         { *m = EndpointRequest{} }
func (m *EndpointRequest) String() string { return proto.CompactTextString(m) }
func (*EndpointRequest) ProtoMessage()    {}
func (*EndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae23ce39a531fe6b, []int{12}
}

func (m *EndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointRequest.Unmarshal(m, b)
}
func (m *EndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointRequest.Marshal(b, m, deterministic)
}
func (m *EndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointRequest.Merge(m, src)
}
func (m *EndpointRequest) XXX_Size() int {
	return xxx_messageInfo_EndpointRequest.Size(m)
}
func (m *EndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointRequest proto.InternalMessageInfo

func (m *EndpointRequest) GetPoll() *PollRequest {
	if m != nil {
		return m.Poll
	}
	return nil
}

func (m *EndpointRequest) GetScan() *ScanRequest {
	if m != nil {
		return m.Scan
	}
	return nil
}

func (m *EndpointRequest) GetStage() *StageRequest {
	if m != nil {
		return m.Stage
	}
	return nil
}

func (m *EndpointRequest) GetSupply() *SupplyRequest {
	if m != nil {
		return m.Supply
	}
	return nil
}

func (m *EndpointRequest) GetTransition() *TransitionRequest {
	if m != nil {
		return m.Transition
	}
	return nil
}

func init() {
	proto.RegisterType((*InitializeRequest)(nil), "remote.InitializeRequest")
	proto.RegisterType((*InitializeResponse)(nil), "remote.InitializeResponse")
	proto.RegisterType((*PollRequest)(nil), "remote.PollRequest")
	proto.RegisterType((*PollCompletionRequest)(nil), "remote.PollCompletionRequest")
	proto.RegisterType((*PollResponse)(nil), "remote.PollResponse")
	proto.RegisterType((*ScanRequest)(nil), "remote.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "remote.ScanResponse")
	proto.RegisterType((*StageRequest)(nil), "remote.StageRequest")
	proto.RegisterType((*StageResponse)(nil), "remote.StageResponse")
	proto.RegisterType((*SupplyRequest)(nil), "remote.SupplyRequest")
	proto.RegisterType((*TransitionRequest)(nil), "remote.TransitionRequest")
	proto.RegisterType((*TransitionResponse)(nil), "remote.TransitionResponse")
	proto.RegisterType((*EndpointRequest)(nil), "remote.EndpointRequest")
}

func init() {
	proto.RegisterFile("session/endpoint/remote/endpoint_protocol.proto", fileDescriptor_ae23ce39a531fe6b)
}

var fileDescriptor_ae23ce39a531fe6b = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5f, 0x6b, 0x13, 0x4b,
	0x14, 0x67, 0x9b, 0xa4, 0x4d, 0x4f, 0x92, 0x7b, 0xdb, 0xb9, 0x4d, 0xef, 0x5a, 0x5f, 0xc2, 0x22,
	0x34, 0x16, 0xba, 0x91, 0x08, 0x95, 0x82, 0x08, 0x35, 0xb6, 0xe0, 0x83, 0x58, 0x26, 0xa2, 0xe0,
	0x8b, 0x4c, 0xb6, 0xd3, 0xcd, 0xe0, 0x64, 0x66, 0x9d, 0x99, 0x0d, 0xc6, 0x0f, 0x25, 0x7e, 0x05,
	0x3f, 0x96, 0x6f, 0x92, 0x99, 0xd9, 0xcd, 0x06, 0xd3, 0x82, 0x6f, 0x7b, 0xce, 0xef, 0x37, 0xe7,
	0xcf, 0xef, 0xcc, 0x9c, 0x85, 0x81, 0xa6, 0x5a, 0x33, 0x29, 0x06, 0x54, 0xdc, 0x64, 0x92, 0x09,
	0x33, 0x50, 0x74, 0x26, 0x0d, 0x2d, 0xed, 0x4f, 0x99, 0x92, 0x46, 0x26, 0x92, 0xc7, 0xf6, 0x03,
	0x6d, 0x3b, 0xfc, 0x08, 0x29, 0xbd, 0x10, 0xc9, 0x80, 0x8a, 0x94, 0x09, 0xea, 0xb0, 0xa3, 0x87,
	0x45, 0xb0, 0x44, 0x8a, 0x5b, 0x96, 0xe6, 0x8a, 0x18, 0x26, 0x85, 0x07, 0xbb, 0x05, 0x38, 0xa7,
	0x4a, 0xaf, 0xdc, 0xc8, 0x86, 0x21, 0x2a, 0x99, 0xb2, 0x79, 0x11, 0x67, 0xdf, 0xfa, 0x92, 0x29,
	0x11, 0x29, 0x5d, 0xa3, 0x65, 0x4a, 0x4e, 0x38, 0x9d, 0x39, 0x5f, 0xf4, 0x33, 0x80, 0xfd, 0xd7,
	0x82, 0x19, 0x46, 0x38, 0xfb, 0x46, 0x31, 0xfd, 0x92, 0x53, 0x6d, 0x10, 0x82, 0xba, 0x92, 0xd2,
	0x84, 0x41, 0x2f, 0xe8, 0xef, 0x62, 0xfb, 0x8d, 0x42, 0xd8, 0xf1, 0xd9, 0xc3, 0x2d, 0xeb, 0x2e,
	0x4c, 0x74, 0x02, 0x3b, 0xbe, 0x9e, 0xb0, 0xd6, 0x0b, 0xfa, 0xff, 0x0c, 0xf7, 0x62, 0x0f, 0xc5,
	0xef, 0x9d, 0x1f, 0x17, 0x04, 0xf4, 0x1c, 0x3a, 0x6b, 0x8d, 0x85, 0xf5, 0x5e, 0xd0, 0x6f, 0x0d,
	0x0f, 0xcb, 0x13, 0xa3, 0x2a, 0x8a, 0xd7, 0xc9, 0xe8, 0x00, 0x1a, 0x84, 0x67, 0x53, 0x12, 0x36,
	0x7a, 0x41, 0xbf, 0x89, 0x9d, 0x11, 0x9d, 0x00, 0xaa, 0xb6, 0xa0, 0x33, 0x29, 0x34, 0x5d, 0x72,
	0xa9, 0x52, 0x52, 0xf9, 0x26, 0x9c, 0x11, 0x75, 0xa0, 0x75, 0x2d, 0x39, 0xf7, 0x8d, 0x46, 0xff,
	0x43, 0x77, 0x69, 0x8e, 0xe4, 0x2c, 0xe3, 0xd4, 0x66, 0xf4, 0xc0, 0x23, 0x68, 0x3b, 0xde, 0xbd,
	0xd1, 0x18, 0xb4, 0xc6, 0x09, 0x29, 0x0e, 0xa1, 0x2b, 0xe8, 0x4e, 0x88, 0xa6, 0x63, 0x41, 0x32,
	0x3d, 0x95, 0x66, 0xcc, 0x52, 0x41, 0x4c, 0xae, 0xa8, 0x3d, 0xd4, 0x1a, 0xee, 0xc5, 0x76, 0xde,
	0x71, 0xe9, 0xc7, 0x9b, 0xe9, 0x4b, 0xf9, 0x6f, 0x73, 0xce, 0xad, 0xce, 0x4d, 0x6c, 0xbf, 0xa3,
	0x1f, 0x01, 0xb4, 0x5d, 0x2e, 0x5f, 0xd1, 0x19, 0x74, 0xb4, 0x3f, 0xf9, 0x8a, 0x72, 0x43, 0xc2,
	0xa0, 0x57, 0xab, 0x24, 0x79, 0x9b, 0xd1, 0x42, 0xc3, 0x35, 0x1a, 0x3a, 0x83, 0xc3, 0x4c, 0x51,
	0x4d, 0xd5, 0x9c, 0xea, 0xcb, 0xaf, 0x34, 0xc9, 0x0d, 0x99, 0x30, 0xce, 0xcc, 0xc2, 0xa7, 0xbb,
	0x03, 0x5d, 0x29, 0x50, 0xab, 0x28, 0x80, 0x8e, 0xa0, 0x69, 0xd4, 0xe2, 0x22, 0x25, 0xcc, 0x8d,
	0xb2, 0x89, 0x4b, 0x3b, 0x7a, 0x01, 0xed, 0xb1, 0x21, 0x69, 0x79, 0xab, 0x0e, 0xa0, 0x91, 0x11,
	0x33, 0xd5, 0xb6, 0xd2, 0x5d, 0xec, 0x8c, 0xe5, 0xbd, 0xba, 0x61, 0x29, 0xd5, 0x46, 0x87, 0x5b,
	0xbd, 0x5a, 0xbf, 0x8d, 0x0b, 0x33, 0x9a, 0x41, 0xc7, 0x9f, 0x5f, 0x0d, 0x61, 0x43, 0x80, 0x27,
	0x00, 0xba, 0x90, 0xce, 0xc5, 0xd8, 0x24, 0x75, 0x85, 0xb3, 0xb9, 0x95, 0xe8, 0x03, 0x74, 0xc6,
	0x79, 0x96, 0xf1, 0xc5, 0xfd, 0xf5, 0xfe, 0x75, 0xba, 0x68, 0x04, 0xfb, 0xef, 0x14, 0x11, 0x9a,
	0x55, 0x2e, 0x18, 0x8a, 0xa1, 0x65, 0x4a, 0xa7, 0xf6, 0xc3, 0x6b, 0xc7, 0x36, 0xcc, 0xc8, 0xbe,
	0x5a, 0x5c, 0x25, 0x44, 0xdf, 0x03, 0x40, 0xd5, 0x28, 0x5e, 0x92, 0x63, 0xd8, 0x51, 0x54, 0xe7,
	0xdc, 0x14, 0x21, 0x3a, 0x2e, 0xc4, 0x85, 0x5b, 0x06, 0xb8, 0x40, 0xd1, 0x63, 0x68, 0xfa, 0x97,
	0x5f, 0x14, 0xed, 0x99, 0xd7, 0xce, 0x8b, 0x4b, 0x18, 0xc5, 0x80, 0xf4, 0x52, 0x77, 0xf5, 0x86,
	0x69, 0xcd, 0x44, 0x7a, 0xc5, 0x38, 0xd5, 0x56, 0xab, 0x26, 0xde, 0x80, 0xac, 0xe4, 0xac, 0x57,
	0xe5, 0xfc, 0x15, 0xc0, 0xbf, 0x97, 0x7e, 0x01, 0x16, 0x4d, 0x1f, 0x43, 0x3d, 0x93, 0x9c, 0xfb,
	0xf7, 0xf0, 0x5f, 0xec, 0xf6, 0x60, 0x5c, 0x79, 0x91, 0xd8, 0x12, 0x96, 0x44, 0x9d, 0x10, 0xb7,
	0x69, 0x2a, 0xc4, 0xca, 0x63, 0xc3, 0x96, 0x80, 0x4e, 0xa0, 0x61, 0x2b, 0xb2, 0xe5, 0xb5, 0x86,
	0x07, 0x25, 0xb3, 0x72, 0xf1, 0xb0, 0xa3, 0xa0, 0x53, 0xd8, 0xd6, 0x76, 0xc0, 0x7e, 0xe9, 0x74,
	0x4b, 0x72, 0x75, 0xec, 0xd8, 0x93, 0xd0, 0x39, 0xc0, 0x6a, 0x00, 0x76, 0xe3, 0xb4, 0x86, 0x0f,
	0x8a, 0x23, 0x7f, 0x0c, 0x14, 0x57, 0xc8, 0x2f, 0xcf, 0x3f, 0x3e, 0x4b, 0x99, 0x99, 0xe6, 0x93,
	0x38, 0x91, 0xb3, 0xc1, 0x94, 0xcc, 0x65, 0x72, 0xca, 0xe4, 0x60, 0x96, 0x2f, 0xeb, 0x10, 0x83,
	0xec, 0x73, 0x7a, 0xd7, 0x3f, 0x63, 0xb2, 0x6d, 0xf7, 0xf2, 0xd3, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x79, 0x77, 0xba, 0x89, 0x55, 0x06, 0x00, 0x00,
}
