// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: synchronization/core/ignore/ignore_syntax.proto

package ignore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IgnoreSyntax specifies the syntax and semantics for ignore specifications.
type IgnoreSyntax int32

const (
	// IgnoreSyntax_IgnoreSyntaxDefault represents an unspecified ignore syntax.
	// It is not valid for use with core synchronization functions. It should be
	// converted to one of the following values based on the desired default
	// behavior.
	IgnoreSyntax_IgnoreSyntaxDefault IgnoreSyntax = 0
	// IgnoreSyntax_IgnoreSyntaxGit specifies that Git-style ignore syntax and
	// semantics should be used.
	IgnoreSyntax_IgnoreSyntaxGit IgnoreSyntax = 1
	// IgnoreSyntax_IgnoreSyntaxDocker specifies that Docker-style ignore syntax
	// and semantics should be used.
	IgnoreSyntax_IgnoreSyntaxDocker IgnoreSyntax = 2
)

// Enum value maps for IgnoreSyntax.
var (
	IgnoreSyntax_name = map[int32]string{
		0: "IgnoreSyntaxDefault",
		1: "IgnoreSyntaxGit",
		2: "IgnoreSyntaxDocker",
	}
	IgnoreSyntax_value = map[string]int32{
		"IgnoreSyntaxDefault": 0,
		"IgnoreSyntaxGit":     1,
		"IgnoreSyntaxDocker":  2,
	}
)

func (x IgnoreSyntax) Enum() *IgnoreSyntax {
	p := new(IgnoreSyntax)
	*p = x
	return p
}

func (x IgnoreSyntax) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IgnoreSyntax) Descriptor() protoreflect.EnumDescriptor {
	return file_synchronization_core_ignore_ignore_syntax_proto_enumTypes[0].Descriptor()
}

func (IgnoreSyntax) Type() protoreflect.EnumType {
	return &file_synchronization_core_ignore_ignore_syntax_proto_enumTypes[0]
}

func (x IgnoreSyntax) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IgnoreSyntax.Descriptor instead.
func (IgnoreSyntax) EnumDescriptor() ([]byte, []int) {
	return file_synchronization_core_ignore_ignore_syntax_proto_rawDescGZIP(), []int{0}
}

var File_synchronization_core_ignore_ignore_syntax_proto protoreflect.FileDescriptor

var file_synchronization_core_ignore_ignore_syntax_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x2f, 0x69, 0x67,
	0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x2a, 0x54, 0x0a, 0x0c, 0x49, 0x67, 0x6e,
	0x6f, 0x72, 0x65, 0x53, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x67, 0x6e,
	0x6f, 0x72, 0x65, 0x53, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x53, 0x79, 0x6e, 0x74,
	0x61, 0x78, 0x47, 0x69, 0x74, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x67, 0x6e, 0x6f, 0x72,
	0x65, 0x53, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x10, 0x02, 0x42,
	0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75,
	0x74, 0x61, 0x67, 0x65, 0x6e, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x75, 0x74, 0x61, 0x67, 0x65, 0x6e,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_synchronization_core_ignore_ignore_syntax_proto_rawDescOnce sync.Once
	file_synchronization_core_ignore_ignore_syntax_proto_rawDescData = file_synchronization_core_ignore_ignore_syntax_proto_rawDesc
)

func file_synchronization_core_ignore_ignore_syntax_proto_rawDescGZIP() []byte {
	file_synchronization_core_ignore_ignore_syntax_proto_rawDescOnce.Do(func() {
		file_synchronization_core_ignore_ignore_syntax_proto_rawDescData = protoimpl.X.CompressGZIP(file_synchronization_core_ignore_ignore_syntax_proto_rawDescData)
	})
	return file_synchronization_core_ignore_ignore_syntax_proto_rawDescData
}

var file_synchronization_core_ignore_ignore_syntax_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_core_ignore_ignore_syntax_proto_goTypes = []interface{}{
	(IgnoreSyntax)(0), // 0: ignore.IgnoreSyntax
}
var file_synchronization_core_ignore_ignore_syntax_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_synchronization_core_ignore_ignore_syntax_proto_init() }
func file_synchronization_core_ignore_ignore_syntax_proto_init() {
	if File_synchronization_core_ignore_ignore_syntax_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_synchronization_core_ignore_ignore_syntax_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_synchronization_core_ignore_ignore_syntax_proto_goTypes,
		DependencyIndexes: file_synchronization_core_ignore_ignore_syntax_proto_depIdxs,
		EnumInfos:         file_synchronization_core_ignore_ignore_syntax_proto_enumTypes,
	}.Build()
	File_synchronization_core_ignore_ignore_syntax_proto = out.File
	file_synchronization_core_ignore_ignore_syntax_proto_rawDesc = nil
	file_synchronization_core_ignore_ignore_syntax_proto_goTypes = nil
	file_synchronization_core_ignore_ignore_syntax_proto_depIdxs = nil
}
