// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: synchronization/core/ignore/syntax.proto

package ignore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Syntax specifies the syntax and semantics for ignore specifications.
type Syntax int32

const (
	// Syntax_SyntaxDefault represents an unspecified ignore syntax. It is not
	// valid for use with core synchronization functions. It should be converted
	// to one of the following values based on the desired default behavior.
	Syntax_SyntaxDefault Syntax = 0
	// Syntax_SyntaxMutagen specifies that Mutagen-style ignore syntax and
	// semantics should be used.
	Syntax_SyntaxMutagen Syntax = 1
	// Syntax_SyntaxDocker specifies that Docker-style ignore syntax and
	// semantics should be used.
	Syntax_SyntaxDocker Syntax = 2
)

// Enum value maps for Syntax.
var (
	Syntax_name = map[int32]string{
		0: "SyntaxDefault",
		1: "SyntaxMutagen",
		2: "SyntaxDocker",
	}
	Syntax_value = map[string]int32{
		"SyntaxDefault": 0,
		"SyntaxMutagen": 1,
		"SyntaxDocker":  2,
	}
)

func (x Syntax) Enum() *Syntax {
	p := new(Syntax)
	*p = x
	return p
}

func (x Syntax) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Syntax) Descriptor() protoreflect.EnumDescriptor {
	return file_synchronization_core_ignore_syntax_proto_enumTypes[0].Descriptor()
}

func (Syntax) Type() protoreflect.EnumType {
	return &file_synchronization_core_ignore_syntax_proto_enumTypes[0]
}

func (x Syntax) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Syntax.Descriptor instead.
func (Syntax) EnumDescriptor() ([]byte, []int) {
	return file_synchronization_core_ignore_syntax_proto_rawDescGZIP(), []int{0}
}

var File_synchronization_core_ignore_syntax_proto protoreflect.FileDescriptor

var file_synchronization_core_ignore_syntax_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x79,
	0x6e, 0x74, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x69, 0x67, 0x6e, 0x6f,
	0x72, 0x65, 0x2a, 0x40, 0x0a, 0x06, 0x53, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x12, 0x11, 0x0a, 0x0d,
	0x53, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x53, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x4d, 0x75, 0x74, 0x61, 0x67, 0x65, 0x6e,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x44, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x10, 0x02, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x75,
	0x74, 0x61, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x68, 0x72,
	0x6f, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x69,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_synchronization_core_ignore_syntax_proto_rawDescOnce sync.Once
	file_synchronization_core_ignore_syntax_proto_rawDescData = file_synchronization_core_ignore_syntax_proto_rawDesc
)

func file_synchronization_core_ignore_syntax_proto_rawDescGZIP() []byte {
	file_synchronization_core_ignore_syntax_proto_rawDescOnce.Do(func() {
		file_synchronization_core_ignore_syntax_proto_rawDescData = protoimpl.X.CompressGZIP(file_synchronization_core_ignore_syntax_proto_rawDescData)
	})
	return file_synchronization_core_ignore_syntax_proto_rawDescData
}

var file_synchronization_core_ignore_syntax_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_core_ignore_syntax_proto_goTypes = []interface{}{
	(Syntax)(0), // 0: ignore.Syntax
}
var file_synchronization_core_ignore_syntax_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_synchronization_core_ignore_syntax_proto_init() }
func file_synchronization_core_ignore_syntax_proto_init() {
	if File_synchronization_core_ignore_syntax_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_synchronization_core_ignore_syntax_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_synchronization_core_ignore_syntax_proto_goTypes,
		DependencyIndexes: file_synchronization_core_ignore_syntax_proto_depIdxs,
		EnumInfos:         file_synchronization_core_ignore_syntax_proto_enumTypes,
	}.Build()
	File_synchronization_core_ignore_syntax_proto = out.File
	file_synchronization_core_ignore_syntax_proto_rawDesc = nil
	file_synchronization_core_ignore_syntax_proto_goTypes = nil
	file_synchronization_core_ignore_syntax_proto_depIdxs = nil
}
