// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/core/conflict.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Conflict encodes conflicting changes on alpha and beta that prevent
// synchronization of a particular path. Conflict objects should be considered
// immutable and must not be modified.
type Conflict struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Root is the root path for the conflict (relative to the synchronization
	// root). While this can (in theory) be computed based on the change lists
	// contained within the conflict, doing so relies on those change lists
	// being constructed and ordered in a particular manner that's not possible
	// to enforce. Additionally, conflicts are often sorted by their root path,
	// and dynamically computing it on every sort comparison operation would be
	// prohibitively expensive.
	Root string `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// AlphaChanges are the relevant changes on alpha.
	AlphaChanges []*Change `protobuf:"bytes,2,rep,name=alphaChanges,proto3" json:"alphaChanges,omitempty"`
	// BetaChanges are the relevant changes on beta.
	BetaChanges   []*Change `protobuf:"bytes,3,rep,name=betaChanges,proto3" json:"betaChanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_synchronization_core_conflict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_synchronization_core_conflict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_synchronization_core_conflict_proto_rawDescGZIP(), []int{0}
}

func (x *Conflict) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *Conflict) GetAlphaChanges() []*Change {
	if x != nil {
		return x.AlphaChanges
	}
	return nil
}

func (x *Conflict) GetBetaChanges() []*Change {
	if x != nil {
		return x.BetaChanges
	}
	return nil
}

var File_synchronization_core_conflict_proto protoreflect.FileDescriptor

const file_synchronization_core_conflict_proto_rawDesc = "" +
	"\n" +
	"#synchronization/core/conflict.proto\x12\x04core\x1a!synchronization/core/change.proto\"\x80\x01\n" +
	"\bConflict\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x120\n" +
	"\falphaChanges\x18\x02 \x03(\v2\f.core.ChangeR\falphaChanges\x12.\n" +
	"\vbetaChanges\x18\x03 \x03(\v2\f.core.ChangeR\vbetaChangesB8Z6github.com/mutagen-io/mutagen/pkg/synchronization/coreb\x06proto3"

var (
	file_synchronization_core_conflict_proto_rawDescOnce sync.Once
	file_synchronization_core_conflict_proto_rawDescData []byte
)

func file_synchronization_core_conflict_proto_rawDescGZIP() []byte {
	file_synchronization_core_conflict_proto_rawDescOnce.Do(func() {
		file_synchronization_core_conflict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_synchronization_core_conflict_proto_rawDesc), len(file_synchronization_core_conflict_proto_rawDesc)))
	})
	return file_synchronization_core_conflict_proto_rawDescData
}

var file_synchronization_core_conflict_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_synchronization_core_conflict_proto_goTypes = []any{
	(*Conflict)(nil), // 0: core.Conflict
	(*Change)(nil),   // 1: core.Change
}
var file_synchronization_core_conflict_proto_depIdxs = []int32{
	1, // 0: core.Conflict.alphaChanges:type_name -> core.Change
	1, // 1: core.Conflict.betaChanges:type_name -> core.Change
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_synchronization_core_conflict_proto_init() }
func file_synchronization_core_conflict_proto_init() {
	if File_synchronization_core_conflict_proto != nil {
		return
	}
	file_synchronization_core_change_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synchronization_core_conflict_proto_rawDesc), len(file_synchronization_core_conflict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_synchronization_core_conflict_proto_goTypes,
		DependencyIndexes: file_synchronization_core_conflict_proto_depIdxs,
		MessageInfos:      file_synchronization_core_conflict_proto_msgTypes,
	}.Build()
	File_synchronization_core_conflict_proto = out.File
	file_synchronization_core_conflict_proto_goTypes = nil
	file_synchronization_core_conflict_proto_depIdxs = nil
}
