// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tunneling/protocol.proto

package tunneling

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// InitializeRequestVersion1 is the data channel initialization request format
// for tunnels with version Version_Version1.
type InitializeRequestVersion1 struct {
	// VersionMajor is the major version component of the tunnel client.
	VersionMajor uint32 `protobuf:"varint,1,opt,name=versionMajor,proto3" json:"versionMajor,omitempty"`
	// VersionMinor is the minor version component of the tunnel client.
	VersionMinor uint32 `protobuf:"varint,2,opt,name=versionMinor,proto3" json:"versionMinor,omitempty"`
	// VersionPatch is the patch version component of the tunnel client.
	VersionPatch uint32 `protobuf:"varint,3,opt,name=versionPatch,proto3" json:"versionPatch,omitempty"`
	// Mode is the mode in which the agent should be run.
	Mode                 string   `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeRequestVersion1) Reset()         { *m = InitializeRequestVersion1{} }
func (m *InitializeRequestVersion1) String() string { return proto.CompactTextString(m) }
func (*InitializeRequestVersion1) ProtoMessage()    {}
func (*InitializeRequestVersion1) Descriptor() ([]byte, []int) {
	return fileDescriptor_f61dcbcd32754015, []int{0}
}

func (m *InitializeRequestVersion1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeRequestVersion1.Unmarshal(m, b)
}
func (m *InitializeRequestVersion1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeRequestVersion1.Marshal(b, m, deterministic)
}
func (m *InitializeRequestVersion1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeRequestVersion1.Merge(m, src)
}
func (m *InitializeRequestVersion1) XXX_Size() int {
	return xxx_messageInfo_InitializeRequestVersion1.Size(m)
}
func (m *InitializeRequestVersion1) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeRequestVersion1.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeRequestVersion1 proto.InternalMessageInfo

func (m *InitializeRequestVersion1) GetVersionMajor() uint32 {
	if m != nil {
		return m.VersionMajor
	}
	return 0
}

func (m *InitializeRequestVersion1) GetVersionMinor() uint32 {
	if m != nil {
		return m.VersionMinor
	}
	return 0
}

func (m *InitializeRequestVersion1) GetVersionPatch() uint32 {
	if m != nil {
		return m.VersionPatch
	}
	return 0
}

func (m *InitializeRequestVersion1) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

// InitializeResponseVersion1 is the data channel initialization response format
// for tunnels with version Version_Version1.
type InitializeResponseVersion1 struct {
	// Error is any error that occurred during initialization. An empty error
	// indicates that initialization was successful and that the connection is
	// ready for use by an endpoint client.
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeResponseVersion1) Reset()         { *m = InitializeResponseVersion1{} }
func (m *InitializeResponseVersion1) String() string { return proto.CompactTextString(m) }
func (*InitializeResponseVersion1) ProtoMessage()    {}
func (*InitializeResponseVersion1) Descriptor() ([]byte, []int) {
	return fileDescriptor_f61dcbcd32754015, []int{1}
}

func (m *InitializeResponseVersion1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeResponseVersion1.Unmarshal(m, b)
}
func (m *InitializeResponseVersion1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeResponseVersion1.Marshal(b, m, deterministic)
}
func (m *InitializeResponseVersion1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeResponseVersion1.Merge(m, src)
}
func (m *InitializeResponseVersion1) XXX_Size() int {
	return xxx_messageInfo_InitializeResponseVersion1.Size(m)
}
func (m *InitializeResponseVersion1) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeResponseVersion1.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeResponseVersion1 proto.InternalMessageInfo

func (m *InitializeResponseVersion1) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*InitializeRequestVersion1)(nil), "tunneling.InitializeRequestVersion1")
	proto.RegisterType((*InitializeResponseVersion1)(nil), "tunneling.InitializeResponseVersion1")
}

func init() { proto.RegisterFile("tunneling/protocol.proto", fileDescriptor_f61dcbcd32754015) }

var fileDescriptor_f61dcbcd32754015 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x29, 0xcd, 0xcb,
	0x4b, 0xcd, 0xc9, 0xcc, 0x4b, 0xd7, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03,
	0x33, 0x84, 0x38, 0xe1, 0x32, 0x4a, 0xb3, 0x19, 0xb9, 0x24, 0x3d, 0xf3, 0x32, 0x4b, 0x32, 0x13,
	0x73, 0x32, 0xab, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xc2, 0x52, 0x8b, 0x8a, 0x33,
	0xf3, 0xf3, 0x0c, 0x85, 0x94, 0xb8, 0x78, 0xca, 0x20, 0x6c, 0xdf, 0xc4, 0xac, 0xfc, 0x22, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xde, 0x20, 0x14, 0x31, 0x64, 0x35, 0x99, 0x79, 0xf9, 0x45, 0x12, 0x4c,
	0xa8, 0x6a, 0x40, 0x62, 0x48, 0x6a, 0x02, 0x12, 0x4b, 0x92, 0x33, 0x24, 0x98, 0x51, 0xd4, 0x80,
	0xc5, 0x84, 0x84, 0xb8, 0x58, 0x72, 0xf3, 0x53, 0x52, 0x25, 0x58, 0x14, 0x18, 0x35, 0x38, 0x83,
	0xc0, 0x6c, 0x25, 0x23, 0x2e, 0x29, 0x64, 0xc7, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0xc2, 0x5d,
	0x27, 0xc2, 0xc5, 0x9a, 0x5a, 0x54, 0x04, 0x75, 0x16, 0x67, 0x10, 0x84, 0xe3, 0xa4, 0x1b, 0xa5,
	0x9d, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x5b, 0x5a, 0x92, 0x98,
	0x9e, 0x9a, 0xa7, 0x9b, 0x99, 0x0f, 0x63, 0xea, 0x17, 0x64, 0xa7, 0xeb, 0xc3, 0x03, 0x20, 0x89,
	0x0d, 0x1c, 0x24, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0x4d, 0x01, 0xbc, 0x2e, 0x01,
	0x00, 0x00,
}
