// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: forwarding/session.proto

package forwarding

import (
	url "github.com/mutagen-io/mutagen/pkg/url"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session represents a forwarding session configuration and persistent state.
// It is mutable within the context of the daemon, so it should be accessed and
// modified in a synchronized fashion. Outside of the daemon (e.g. when returned
// via the API), it should be considered immutable.
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier is the (unique) session identifier. It is static. It cannot be
	// empty.
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Version is the session version. It is static.
	Version Version `protobuf:"varint,2,opt,name=version,proto3,enum=forwarding.Version" json:"version,omitempty"`
	// CreationTime is the creation time of the session. It is static. It cannot
	// be nil.
	CreationTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	// CreatingVersionMajor is the major version component of the version of
	// Mutagen which created the session. It is static.
	CreatingVersionMajor uint32 `protobuf:"varint,4,opt,name=creatingVersionMajor,proto3" json:"creatingVersionMajor,omitempty"`
	// CreatingVersionMinor is the minor version component of the version of
	// Mutagen which created the session. It is static.
	CreatingVersionMinor uint32 `protobuf:"varint,5,opt,name=creatingVersionMinor,proto3" json:"creatingVersionMinor,omitempty"`
	// CreatingVersionPatch is the patch version component of the version of
	// Mutagen which created the session. It is static.
	CreatingVersionPatch uint32 `protobuf:"varint,6,opt,name=creatingVersionPatch,proto3" json:"creatingVersionPatch,omitempty"`
	// Source is the source endpoint URL. It is static. It cannot be nil.
	Source *url.URL `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	// Destination is the destination endpoint URL. It is static. It cannot be
	// nil.
	Destination *url.URL `protobuf:"bytes,8,opt,name=destination,proto3" json:"destination,omitempty"`
	// Configuration is the flattened session configuration. It is static. It
	// cannot be nil.
	Configuration *Configuration `protobuf:"bytes,9,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// ConfigurationSource are the source-specific session configuration
	// overrides. It is static.
	ConfigurationSource *Configuration `protobuf:"bytes,10,opt,name=configurationSource,proto3" json:"configurationSource,omitempty"`
	// ConfigurationDestination are the destination-specific session
	// configuration overrides. It is static.
	ConfigurationDestination *Configuration `protobuf:"bytes,11,opt,name=configurationDestination,proto3" json:"configurationDestination,omitempty"`
	// Name is a user-friendly name for the session. It may be empty and is not
	// guaranteed to be unique across all sessions. It is only used as a simpler
	// handle for specifying sessions. It is static.
	Name string `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	// Labels are the session labels. They are static.
	Labels map[string]string `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Paused indicates whether or not the session is marked as paused.
	Paused        bool `protobuf:"varint,14,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_forwarding_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_forwarding_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_forwarding_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Session) GetVersion() Version {
	if x != nil {
		return x.Version
	}
	return Version_Invalid
}

func (x *Session) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *Session) GetCreatingVersionMajor() uint32 {
	if x != nil {
		return x.CreatingVersionMajor
	}
	return 0
}

func (x *Session) GetCreatingVersionMinor() uint32 {
	if x != nil {
		return x.CreatingVersionMinor
	}
	return 0
}

func (x *Session) GetCreatingVersionPatch() uint32 {
	if x != nil {
		return x.CreatingVersionPatch
	}
	return 0
}

func (x *Session) GetSource() *url.URL {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Session) GetDestination() *url.URL {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Session) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *Session) GetConfigurationSource() *Configuration {
	if x != nil {
		return x.ConfigurationSource
	}
	return nil
}

func (x *Session) GetConfigurationDestination() *Configuration {
	if x != nil {
		return x.ConfigurationDestination
	}
	return nil
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Session) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

var File_forwarding_session_proto protoreflect.FileDescriptor

const file_forwarding_session_proto_rawDesc = "" +
	"\n" +
	"\x18forwarding/session.proto\x12\n" +
	"forwarding\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eforwarding/configuration.proto\x1a\x18forwarding/version.proto\x1a\rurl/url.proto\"\x87\x06\n" +
	"\aSession\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12-\n" +
	"\aversion\x18\x02 \x01(\x0e2\x13.forwarding.VersionR\aversion\x12>\n" +
	"\fcreationTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationTime\x122\n" +
	"\x14creatingVersionMajor\x18\x04 \x01(\rR\x14creatingVersionMajor\x122\n" +
	"\x14creatingVersionMinor\x18\x05 \x01(\rR\x14creatingVersionMinor\x122\n" +
	"\x14creatingVersionPatch\x18\x06 \x01(\rR\x14creatingVersionPatch\x12 \n" +
	"\x06source\x18\a \x01(\v2\b.url.URLR\x06source\x12*\n" +
	"\vdestination\x18\b \x01(\v2\b.url.URLR\vdestination\x12?\n" +
	"\rconfiguration\x18\t \x01(\v2\x19.forwarding.ConfigurationR\rconfiguration\x12K\n" +
	"\x13configurationSource\x18\n" +
	" \x01(\v2\x19.forwarding.ConfigurationR\x13configurationSource\x12U\n" +
	"\x18configurationDestination\x18\v \x01(\v2\x19.forwarding.ConfigurationR\x18configurationDestination\x12\x12\n" +
	"\x04name\x18\f \x01(\tR\x04name\x127\n" +
	"\x06labels\x18\r \x03(\v2\x1f.forwarding.Session.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06paused\x18\x0e \x01(\bR\x06paused\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B.Z,github.com/mutagen-io/mutagen/pkg/forwardingb\x06proto3"

var (
	file_forwarding_session_proto_rawDescOnce sync.Once
	file_forwarding_session_proto_rawDescData []byte
)

func file_forwarding_session_proto_rawDescGZIP() []byte {
	file_forwarding_session_proto_rawDescOnce.Do(func() {
		file_forwarding_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forwarding_session_proto_rawDesc), len(file_forwarding_session_proto_rawDesc)))
	})
	return file_forwarding_session_proto_rawDescData
}

var file_forwarding_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forwarding_session_proto_goTypes = []any{
	(*Session)(nil),               // 0: forwarding.Session
	nil,                           // 1: forwarding.Session.LabelsEntry
	(Version)(0),                  // 2: forwarding.Version
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*url.URL)(nil),               // 4: url.URL
	(*Configuration)(nil),         // 5: forwarding.Configuration
}
var file_forwarding_session_proto_depIdxs = []int32{
	2, // 0: forwarding.Session.version:type_name -> forwarding.Version
	3, // 1: forwarding.Session.creationTime:type_name -> google.protobuf.Timestamp
	4, // 2: forwarding.Session.source:type_name -> url.URL
	4, // 3: forwarding.Session.destination:type_name -> url.URL
	5, // 4: forwarding.Session.configuration:type_name -> forwarding.Configuration
	5, // 5: forwarding.Session.configurationSource:type_name -> forwarding.Configuration
	5, // 6: forwarding.Session.configurationDestination:type_name -> forwarding.Configuration
	1, // 7: forwarding.Session.labels:type_name -> forwarding.Session.LabelsEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_forwarding_session_proto_init() }
func file_forwarding_session_proto_init() {
	if File_forwarding_session_proto != nil {
		return
	}
	file_forwarding_configuration_proto_init()
	file_forwarding_version_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forwarding_session_proto_rawDesc), len(file_forwarding_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_forwarding_session_proto_goTypes,
		DependencyIndexes: file_forwarding_session_proto_depIdxs,
		MessageInfos:      file_forwarding_session_proto_msgTypes,
	}.Build()
	File_forwarding_session_proto = out.File
	file_forwarding_session_proto_goTypes = nil
	file_forwarding_session_proto_depIdxs = nil
}
