// Code generated by protoc-gen-go.
// source: entry.proto
// DO NOT EDIT!

package sync

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EntryKind int32

const (
	EntryKind_Directory EntryKind = 0
	EntryKind_File      EntryKind = 1
)

var EntryKind_name = map[int32]string{
	0: "Directory",
	1: "File",
}
var EntryKind_value = map[string]int32{
	"Directory": 0,
	"File":      1,
}

func (x EntryKind) String() string {
	return proto.EnumName(EntryKind_name, int32(x))
}
func (EntryKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type Entry struct {
	Kind       EntryKind         `protobuf:"varint,1,opt,name=kind,enum=sync.EntryKind" json:"kind,omitempty"`
	Executable bool              `protobuf:"varint,2,opt,name=executable" json:"executable,omitempty"`
	Digest     []byte            `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Contents   map[string]*Entry `protobuf:"bytes,4,rep,name=contents" json:"contents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Entry) GetKind() EntryKind {
	if m != nil {
		return m.Kind
	}
	return EntryKind_Directory
}

func (m *Entry) GetExecutable() bool {
	if m != nil {
		return m.Executable
	}
	return false
}

func (m *Entry) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *Entry) GetContents() map[string]*Entry {
	if m != nil {
		return m.Contents
	}
	return nil
}

type OrderedEntry struct {
	Kind       EntryKind              `protobuf:"varint,1,opt,name=kind,enum=sync.EntryKind" json:"kind,omitempty"`
	Executable bool                   `protobuf:"varint,2,opt,name=executable" json:"executable,omitempty"`
	Digest     []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Contents   []*OrderedEntryContent `protobuf:"bytes,4,rep,name=contents" json:"contents,omitempty"`
}

func (m *OrderedEntry) Reset()                    { *m = OrderedEntry{} }
func (m *OrderedEntry) String() string            { return proto.CompactTextString(m) }
func (*OrderedEntry) ProtoMessage()               {}
func (*OrderedEntry) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *OrderedEntry) GetKind() EntryKind {
	if m != nil {
		return m.Kind
	}
	return EntryKind_Directory
}

func (m *OrderedEntry) GetExecutable() bool {
	if m != nil {
		return m.Executable
	}
	return false
}

func (m *OrderedEntry) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *OrderedEntry) GetContents() []*OrderedEntryContent {
	if m != nil {
		return m.Contents
	}
	return nil
}

type OrderedEntryContent struct {
	Name  string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Entry *OrderedEntry `protobuf:"bytes,2,opt,name=entry" json:"entry,omitempty"`
}

func (m *OrderedEntryContent) Reset()                    { *m = OrderedEntryContent{} }
func (m *OrderedEntryContent) String() string            { return proto.CompactTextString(m) }
func (*OrderedEntryContent) ProtoMessage()               {}
func (*OrderedEntryContent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *OrderedEntryContent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderedEntryContent) GetEntry() *OrderedEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "sync.Entry")
	proto.RegisterType((*OrderedEntry)(nil), "sync.OrderedEntry")
	proto.RegisterType((*OrderedEntryContent)(nil), "sync.OrderedEntryContent")
	proto.RegisterEnum("sync.EntryKind", EntryKind_name, EntryKind_value)
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x92, 0x4f, 0x4a, 0xec, 0x40,
	0x10, 0x87, 0x5f, 0x4f, 0x92, 0x21, 0xa9, 0xcc, 0x3c, 0x43, 0x09, 0x12, 0x5d, 0x48, 0x8c, 0x2e,
	0x82, 0x8b, 0x2c, 0x22, 0x82, 0xb8, 0xf5, 0x0f, 0x82, 0x0b, 0xa1, 0x3d, 0x41, 0x26, 0x29, 0xa4,
	0x99, 0xd8, 0x91, 0x4e, 0x8f, 0x98, 0xeb, 0x78, 0x37, 0xef, 0x21, 0xe9, 0x34, 0x63, 0x44, 0xf7,
	0xee, 0xaa, 0xea, 0x2b, 0x2a, 0xbf, 0x8f, 0x34, 0x84, 0x24, 0xb5, 0xea, 0xf3, 0x17, 0xd5, 0xea,
	0x16, 0xdd, 0xae, 0x97, 0x55, 0xfa, 0xc1, 0xc0, 0xbb, 0x19, 0xa6, 0x78, 0x0c, 0xee, 0x5a, 0xc8,
	0x3a, 0x66, 0x09, 0xcb, 0xfe, 0x17, 0x3b, 0xf9, 0x80, 0x73, 0x83, 0xee, 0x85, 0xac, 0xb9, 0x81,
	0x78, 0x08, 0x40, 0x6f, 0x54, 0x6d, 0x74, 0xb9, 0x6a, 0x28, 0x9e, 0x25, 0x2c, 0xf3, 0xf9, 0x64,
	0x82, 0x7b, 0x30, 0xaf, 0xc5, 0x13, 0x75, 0x3a, 0x76, 0x12, 0x96, 0x2d, 0xb8, 0xed, 0xf0, 0x1c,
	0xfc, 0xaa, 0x95, 0x9a, 0xa4, 0xee, 0x62, 0x37, 0x71, 0xb2, 0xb0, 0xd8, 0x9f, 0x7c, 0x20, 0xbf,
	0xb2, 0xcc, 0x74, 0x7c, 0xbb, 0x7a, 0x70, 0x07, 0xcb, 0x6f, 0x08, 0x23, 0x70, 0xd6, 0xd4, 0x9b,
	0x8c, 0x01, 0x1f, 0x4a, 0x3c, 0x02, 0xef, 0xb5, 0x6c, 0x36, 0x63, 0x98, 0xb0, 0x08, 0x27, 0x67,
	0xf9, 0x48, 0x2e, 0x67, 0x17, 0x2c, 0x7d, 0x67, 0xb0, 0x78, 0x50, 0x35, 0x29, 0xaa, 0xff, 0x52,
	0x77, 0x1a, 0xc1, 0x9a, 0x7d, 0xe9, 0xa6, 0x8f, 0xb0, 0xfb, 0xcb, 0x02, 0x22, 0xb8, 0xb2, 0x7c,
	0x26, 0x6b, 0x6d, 0x6a, 0xcc, 0xc0, 0x33, 0x3f, 0xd3, 0x6a, 0xe3, 0xcf, 0xf3, 0x7c, 0x5c, 0x38,
	0x3d, 0x81, 0x60, 0xab, 0x85, 0x4b, 0x08, 0xae, 0x85, 0xa2, 0x4a, 0xb7, 0xaa, 0x8f, 0xfe, 0xa1,
	0x0f, 0xee, 0xad, 0x68, 0x28, 0x62, 0xab, 0xb9, 0x79, 0x14, 0x67, 0x9f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xaf, 0x84, 0x6c, 0xf1, 0x23, 0x02, 0x00, 0x00,
}
