// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/version.proto

package synchronization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Version specifies a session version, providing default behavior that can vary
// without affecting existing sessions.
type Version int32

const (
	// Invalid is the default session version and represents an unspecfied and
	// invalid version. It is used as a sanity check to ensure that version is
	// set for a session.
	Version_Invalid Version = 0
	// Version1 represents session version 1.
	Version_Version1 Version = 1
)

// Enum value maps for Version.
var (
	Version_name = map[int32]string{
		0: "Invalid",
		1: "Version1",
	}
	Version_value = map[string]int32{
		"Invalid":  0,
		"Version1": 1,
	}
)

func (x Version) Enum() *Version {
	p := new(Version)
	*p = x
	return p
}

func (x Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Version) Descriptor() protoreflect.EnumDescriptor {
	return file_synchronization_version_proto_enumTypes[0].Descriptor()
}

func (Version) Type() protoreflect.EnumType {
	return &file_synchronization_version_proto_enumTypes[0]
}

func (x Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Version.Descriptor instead.
func (Version) EnumDescriptor() ([]byte, []int) {
	return file_synchronization_version_proto_rawDescGZIP(), []int{0}
}

var File_synchronization_version_proto protoreflect.FileDescriptor

const file_synchronization_version_proto_rawDesc = "" +
	"\n" +
	"\x1dsynchronization/version.proto\x12\x0fsynchronization*$\n" +
	"\aVersion\x12\v\n" +
	"\aInvalid\x10\x00\x12\f\n" +
	"\bVersion1\x10\x01B3Z1github.com/mutagen-io/mutagen/pkg/synchronizationb\x06proto3"

var (
	file_synchronization_version_proto_rawDescOnce sync.Once
	file_synchronization_version_proto_rawDescData []byte
)

func file_synchronization_version_proto_rawDescGZIP() []byte {
	file_synchronization_version_proto_rawDescOnce.Do(func() {
		file_synchronization_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_synchronization_version_proto_rawDesc), len(file_synchronization_version_proto_rawDesc)))
	})
	return file_synchronization_version_proto_rawDescData
}

var file_synchronization_version_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_version_proto_goTypes = []any{
	(Version)(0), // 0: synchronization.Version
}
var file_synchronization_version_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_synchronization_version_proto_init() }
func file_synchronization_version_proto_init() {
	if File_synchronization_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synchronization_version_proto_rawDesc), len(file_synchronization_version_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_synchronization_version_proto_goTypes,
		DependencyIndexes: file_synchronization_version_proto_depIdxs,
		EnumInfos:         file_synchronization_version_proto_enumTypes,
	}.Build()
	File_synchronization_version_proto = out.File
	file_synchronization_version_proto_goTypes = nil
	file_synchronization_version_proto_depIdxs = nil
}
